import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,copyFileSync} from 'node:fs';
import {cards,cardCatalog} from '@workspace/squabblemon-engine/data';
import {SELECTED_WAVE} from '../../lib/squabblemon-engine/src/selectedWave';
const out=process.argv[2];if(!out)throw Error('Output required');
const read=(name:string)=>JSON.parse(readFileSync(`${out}/${name}`,'utf8'));
const baseline=JSON.parse(readFileSync(process.argv[3],'utf8'));
const before=read('before/sweep.json'), after=read('after/sweep.json');
const eligible=cardCatalog.filter(c=>c.engineId!=='guap'&&c.kind!=='token'&&!c.hazard);
assert.deepEqual(after.cards.map((c:any)=>c.id).sort(),eligible.map(c=>c.engineId).sort());
assert.equal(after.failures.length,0);assert.equal(before.failures.length,0);
assert(after.cards.every((c:any)=>c.games===32));
assert.deepEqual(cards.guap,baseline.cards.guap);
const approved=['track-suit-auntie','gym-bag-yn','stairwell-sprinter','last-set-og','tour-van-driver','mixtape-cousin','merch-table-hustler'];
for(const id of approved) assert.deepEqual(cards[id],baseline.cards[id],id+' retains approved kit');
const changed=Object.keys(cards).filter(id=>JSON.stringify(cards[id])!==JSON.stringify(baseline.cards[id]));
assert(changed.every(id=>SELECTED_WAVE.some(([x])=>x===id)),'No unrelated old kit changed');
const rows=cardCatalog.map(c=>{
 const observation=after.cards.find((x:any)=>x.id===c.engineId);
 const decision=c.engineId==='guap'?'Excluded: explicitly protected':changed.includes(c.engineId)?'Adjusted: bounded new-card setup/payoff':'Retained: kit/budget unchanged after complete screen';
 return {id:c.engineId,name:c.name,kind:c.kind,cost:c.cost,power:c.power,decision,effect:c.effect,priorEffect:baseline.cards[c.engineId]?.effect,priorCost:baseline.cards[c.engineId]?.cost,priorPower:baseline.cards[c.engineId]?.power,observations:observation?.games??0,authoredShells:observation?.authoredShells??[],diagnosticInsertion:observation?.injected??false,played:observation?.played??0,shellScore:observation?.score??null,reusedUnchangedComposition:!!observation?.reusedBaseline};
});
const csv=(v:any)=>'"'+String(v??'').replaceAll('"','""')+'"';
const columns=['id','name','kind','cost','power','decision','observations','played','shellScore','diagnosticInsertion','reusedUnchangedComposition','effect'];
writeFileSync(`${out}/all-card-decisions.csv`,[columns.join(','),...rows.map(r=>columns.map(k=>csv((r as any)[k])).join(','))].join('\n')+'\n');
writeFileSync(`${out}/all-card-decisions.json`,JSON.stringify(rows,null,2));
copyFileSync(process.argv[3],`${out}/release-baseline.json`);
const baseNew=read('new-before/summary.json');const first=read('new-candidate/summary.json');const family=read('family-candidate-3/summary.json');const heldBefore=read('heldout-before/summary.json');const heldAfter=read('heldout-after/summary.json');
assert.equal(baseNew.coverage.length,31);assert(baseNew.coverage.every((c:any)=>c.observations>0&&c.played>0));
const comparisons=baseNew.summary.map((s:any)=>({deck:s.deck,screenBefore:s.score,screenAfter:(s.deck==='sunday-dinner'?family:first).summary.find((r:any)=>r.deck===s.deck).score,heldoutBefore:heldBefore.summary.find((r:any)=>r.deck===s.deck).score,heldoutAfter:heldAfter.summary.find((r:any)=>r.deck===s.deck).score}));
const meta={baselineCommit:'692c2d37afe0c3b564e73e4e8d923707480d4579',catalog:cardCatalog.length,target:300,reservedSlots:300-cardCatalog.length,considered:eligible.length,excluded:['guap'],changed,approvedPreserved:approved,beforeIndependentSimulations:before.uniqueSimulations,afterIndependentSimulations:after.uniqueSimulations,reusedUnchangedCardRows:after.cards.filter((c:any)=>c.reusedBaseline).length,scenarioObservationsPerArm:after.cards.reduce((n:number,c:any)=>n+c.games,0),comparisons,failures:after.failures};
writeFileSync(`${out}/summary.json`,JSON.stringify(meta,null,2));console.log(JSON.stringify(meta,null,2));
