import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import path from 'node:path';
import {cards} from '@workspace/squabblemon-engine/data';
import {authoredRankingDecks} from './all-decks-ranking-decks';
import {root,sourceHash,type RankingPlan} from './all-decks-ranking';
import {validateCoverage} from './all-decks-ranking-report';
const directory=path.resolve(root,process.argv[2]);
const plan=JSON.parse(readFileSync(path.join(directory,'plan.json'),'utf8')) as RankingPlan;
assert.equal(sourceHash(),plan.sourceHash); assert.equal(validateCoverage(plan),16); assert.deepEqual(plan.excludedCardIds,[]);
for(const d of authoredRankingDecks())assert(plan.decks.some(p=>[...p.cardIds].sort().join('|')===[...d.cardIds].sort().join('|')),`Missing ${d.id}`);
const red=plan.decks.find(d=>d.id==='focused-red-set')!;
assert(red.cardIds.includes('guap')&&red.cardIds.includes('folks'));
for(const id of ['starter-sunday-dinner','starter-fitness-routes','starter-fitness-circuit','starter-music-tour','starter-music-industry','starter-community-table','starter-squabblehouse-shift'])assert(plan.decks.some(d=>d.id===id));
const missingCase=structuredClone(plan);missingCase.cases.pop();assert.throws(()=>validateCoverage(missingCase));
const duplicate=structuredClone(plan);duplicate.cases[1]=duplicate.cases[0];assert.throws(()=>validateCoverage(duplicate));
const included=new Set(plan.decks.flatMap(d=>d.cardIds));
const collectible=Object.entries(cards).filter(([,c])=>c.kind!=='token'&&!c.hazard);
const coverage=JSON.parse(readFileSync(path.join(directory,'coverage.json'),'utf8'));
coverage.unrepresentedCards=collectible.filter(([id])=>!included.has(id)).map(([id,c])=>({id,catalogId:c.id,name:c.name}));
assert.equal(coverage.unrepresentedCards.length+included.size,collectible.length);
writeFileSync(path.join(directory,'coverage.json'),JSON.stringify(coverage,null,2)+'\n');
console.log(JSON.stringify({verifiedRecipes:plan.decks.length,cases:plan.cases.length,represented:included.size,remaining:coverage.unrepresentedCards.length,total:collectible.length,negativeCoverageChecks:2}));
