import type { Card } from './data';
/** v52: base-card budgets. Mechanic identities and collection IDs remain stable. */
export const BASE_PVP_VALUES: Readonly<Record<string, Partial<Pick<Card,'cost'|'power'>>>> = {
  "abuela":{"power":2},
  "alice":{"cost":2,"power":1},
  "apartment-maintenance-sage":{"power":4},
  "ashlee":{"power":2},
  "baby":{"power":5},
  "bail-bonds-auntie":{"power":3},
  "barber":{"power":5},
  "barbershop-heckler":{"power":2},
  "bbldemon":{"power":4},
  "bblnice":{"power":4},
  "bboy":{"power":1},
  "big-sister":{"power":3},
  "bigzoey":{"power":2},
  "bikelife":{"power":4},
  "block-spinner":{"power":3},
  "blue-nose-pit":{"power":5},
  "blueside1":{"power":2},
  "bluetooth-unc":{"power":2},
  "booster":{"power":2},
  "bossbabe":{"cost":2,"power":4},
  "bouncer":{"power":1},
  "buddy":{"power":3},
  "calisthenics-yn":{"power":4},
  "cane-corso-red":{"power":6},
  "canopykeeper":{"power":2},
  "captainjigga":{"power":3},
  "cheshire":{"power":1},
  "chessregular":{"power":1},
  "church":{"power":1},
  "church-aunties-rival":{"power":3},
  "circuitcaptain":{"power":4},
  "cloudbreak":{"power":2},
  "community-cook":{"power":4},
  "conductor":{"power":1},
  "cornball":{"power":2},
  "cornercoach":{"power":1},
  "counter":{"power":6},
  "cousin-back-from-college":{"power":3},
  "crazy-ex-boyfriend":{"power":5},
  "crossingguard":{"power":2},
  "crosswind":{"power":1},
  "dancecaptain":{"power":4},
  "delivery-app-cyclist":{"power":2},
  "demario":{"power":5},
  "demon-trainer":{"power":6},
  "dorothy":{"power":2},
  "drfade":{"cost":3,"power":5},
  "failedathlete":{"power":4},
  "fein":{"power":4},
  "fitness-bro":{"power":3},
  "fitness-girl":{"power":3},
  "folks":{"power":2},
  "foodz":{"power":5},
  "gamer":{"power":1},
  "ganger-red":{"cost":2,"power":5},
  "gardener":{"power":1},
  "gardenwall":{"power":1},
  "godofhookah":{"power":3},
  "gothkid":{"power":5},
  "grandma-said-sit-down":{"power":6},
  "griddle-master":{"power":2},
  "grill-uncle":{"power":5},
  "group-chat-instigator":{"power":5},
  "gust":{"power":2},
  "gym-spotter-yn":{"power":4},
  "hair-stylist":{"power":3},
  "he-just-a-friend":{"power":4},
  "homeless-wiseman":{"power":2},
  "homelessguy":{"power":5},
  "homelesslegend":{"power":7},
  "homelessyn":{"power":2},
  "honestthot":{"power":1},
  "hooper":{"cost":4,"power":4},
  "icecream":{"power":7},
  "inmate-boyfriend":{"power":2},
  "inmate-contraband":{"power":4},
  "inmate-crafty":{"power":4},
  "inmate-informant":{"power":3},
  "inmate-kingpin":{"power":5},
  "johnhenry":{"power":6},
  "jump-rope-menace":{"power":3},
  "krump":{"power":1},
  "kyle":{"power":3},
  "landlord":{"power":3},
  "lash-tech":{"power":3},
  "last-set-og":{"power":5},
  "laundry":{"power":4},
  "lebron-james":{"power":3},
  "leroy":{"cost":3,"power":5},
  "lion":{"power":3},
  "look-out":{"power":3},
  "luigion":{"power":6},
  "madhatter":{"power":1},
  "mansamusa":{"power":3},
  "merch-table-hustler":{"power":2},
  "mixtape-cousin":{"power":1},
  "monsoonanchor":{"power":2},
  "mrrabbit":{"cost":2,"power":1},
  "ms-mary-mack":{"power":5},
  "nerd":{"power":5},
  "night-bus-driver":{"power":2},
  "nightmedic":{"power":3},
  "og":{"power":4},
  "og-calisthenics":{"power":5},
  "ogdominican":{"power":3},
  "oink":{"cost":4,"power":4},
  "one-man-band":{"power":5},
  "oz":{"cost":4,"power":5},
  "personal-trainer":{"power":4},
  "pinaynurse":{"cost":2,"power":4},
  "piratedj":{"power":2},
  "plate-auntie":{"power":3},
  "plug":{"power":3},
  "promoter":{"power":2},
  "ptang":{"power":3},
  "queenofhearts":{"power":1},
  "rastamon":{"power":5},
  "redneck-evil":{"cost":4},
  "track-suit-auntie":{"power":2},
  "gym-bag-yn":{"power":3},
  "stairwell-sprinter":{"power":3},
  "redpill":{"power":2},
  "redside1":{"power":3},
  "redside5":{"cost":2,"power":4},
  "repoman":{"power":1},
  "riptidebruiser":{"power":1},
  "roaster":{"power":3},
  "rootnurse":{"power":1},
  "seafoodassassin":{"power":4},
  "second-plate-cousin":{"power":4},
  "sherlock":{"power":4},
  "shonuff":{"power":1},
  "side-chick":{"power":2},
  "simmy":{"power":8},
  "slipstream":{"power":2},
  "snow":{"power":6},
  "sportsprodigy":{"power":5},
  "sprout":{"power":2},
  "squabble-house-manager":{"power":1},
  "squabblehouse-bus-boy":{"power":1},
  "squabblehouse-cashier":{"power":1},
  "stillwatermedic":{"power":1},
  "stockz":{"power":4},
  "stonersr":{"power":7},
  "streamer":{"power":5},
  "stud":{"power":7},
  "studio-couch-yn":{"power":1},
  "suga-mama":{"power":4},
  "tayaty":{"cost":3,"power":3},
  "techbro":{"power":5},
  "the-battle-rapper":{"power":6},
  "the-dj":{"power":3},
  "the-favorite-grandchild":{"power":2},
  "the-hype-man":{"power":1},
  "the-janky-promoter":{"power":4},
  "the-local-celebrity":{"power":6},
  "the-manager-evil":{"power":5},
  "the-manager-nice":{"power":4},
  "the-og-rap-legend":{"cost":5,"power":6},
  "the-opening-act":{"power":2},
  "the-rapper":{"cost":3,"power":3},
  "thefeds":{"power":1},
  "tinman":{"power":3},
  "torta":{"power":1},
  "triple-og-red":{"power":8},
  "tron":{"power":2},
  "uncle-sam":{"power":6},
  "vibe":{"power":5},
  "watson":{"power":4},
  "wifey":{"cost":3,"power":3},
  "wiretap":{"power":1},
  "work-hubby":{"power":4},
  "yasuke":{"power":1},
  "youngbull":{"power":4},
};
export const PVP_SUPPORT = { transfer:2, soulFood:3, cognac:3, fireCognac:4, wristCheck:1 } as const;
export function applyBasePvpBalance(cards:Record<string,Card>) {
  for(const [id,patch] of Object.entries(BASE_PVP_VALUES)) {
    if(!cards[id])throw new Error(`Missing base PvP card: ${id}`);
    Object.assign(cards[id],patch);
  }
  cards['ganger-blue'].effect='On Reveal: Give your weakest Blue Set ally in another district +5 Hands and Protection, and gain +1 Hand. If there is no remote Blue Set ally, give your weakest other remote ally +3 Hands and Protection. With no remote ally, gain +1 Hand.';
  cards['look-out'].effect=cards['look-out'].effect.replace('ally +2 Hands', 'ally +3 Hands');
  cards['ganger-red'].effect='On Reveal: Deal 2 damage to the strongest enemy here that can lose Hands. If damage lands or this attack consumes Protection, gain +1 Hand.';
  cards['cane-corso-red'].effect=cards['cane-corso-red'].effect.replace('the strongest enemy here loses', 'the strongest enemy here that can lose Hands loses');
  cards.monsoonanchor.effect='Ongoing: While in your hand, your weakest other Water character in each district gains +1 Hand at round end. On Reveal: Weaken the strongest enemy here.';
  cards.godofhookah.effect='On Reveal: Apply 1 Burn to the weakest unburned enemy character in another district. Ongoing: At round end, the first enemy damaged by Burn in each district passes 1 Burn to the weakest unburned enemy in the next district. New Burn waits until next round. If that district has enemies but all were already burning, gain +1 Hand, at most once per round.';
  cards.foodz.effect='On Reveal: Cleanse every other friendly character on your board. Give your weakest other character in each district +2 Hands. Give an extra +2 to the weakest Light ally actually cleansed.';
  cards.tayaty.effect='On Reveal: Gain +1 Hand, then repeat the last resolved On Reveal if it is repeatable, using Tayaty as its source. If it cannot be repeated, gain Protection instead. Persistent creative contracts cannot be re-armed.';
  cards.buspass.effect=`On Reveal: Issue a Transfer Ticket. Your next character costs 1 less Motion and arrives with +${PVP_SUPPORT.transfer} Hands. Supports cannot spend the ticket.`;
  cards.soulfood.effect=`On Reveal: Cleanse your weakest afflicted friendly character here, or your weakest if nobody is afflicted, and give it +${PVP_SUPPORT.soulFood} Hands.`;
  cards.cognac.effect=`On Reveal: Give your weakest friendly character here +${PVP_SUPPORT.cognac} Hands, or +${PVP_SUPPORT.fireCognac} if it is Fire.`;
  cards.bustdown.effect=`On Reveal: Give your weakest friendly character here +${PVP_SUPPORT.wristCheck} Hand and Protection. If this ward blocks a hostile ability, its wearer gains +2 Hands once. Other shields do not cash this watch.`;
}
