import type { AbilityUpgradeEffect, Card, CardRarity } from "./data";

export const BLOCKBUSTER_CHARACTERS = [
  [
    "miami-surgeon",
    "Miami Surgeon",
    "Rare",
    "Water",
    3,
    3,
    "Clean Work",
    "Cleanse your weakest other ally here and give it +2 Hands.",
  ],
  [
    "roommate",
    "Roommate",
    "Common",
    "Normal",
    1,
    2,
    "Your Side of the Fridge",
    "If another ally is here, gain +1 Hand.",
  ],
  [
    "ahki",
    "Ahki",
    "Uncommon",
    "Light",
    2,
    2,
    "The Usual",
    "Give your weakest other ally here +2 Hands.",
  ],
  [
    "mr-trick",
    "Mr. Trick",
    "Rare",
    "Dark",
    3,
    3,
    "Bottle Service",
    "Spend up to 2 remaining Motion. Give your weakest other ally here that many Hands.",
  ],
  [
    "dr-umah",
    "Dr. Umah",
    "Epic",
    "Light",
    3,
    3,
    "Build Together",
    "Give every other friendly character here +1 Hand.",
  ],
  [
    "atl-scammer",
    "ATL Scammer",
    "Rare",
    "Dark",
    3,
    2,
    "Show the Receipts",
    "Take up to 1 Motion from your rival, then gain +1 Hand if any Motion was taken.",
  ],
  [
    "hater",
    "Hater",
    "Common",
    "Dark",
    1,
    2,
    "Always Something",
    "Give the strongest enemy here -1 Hand.",
  ],
  [
    "teacher",
    "Teacher Who Never Believed in Rappers",
    "Rare",
    "Earth",
    3,
    3,
    "Still Rapping?",
    "Silence the strongest enemy here.",
  ],
  [
    "tattoo-artist",
    "Tattoo Artist",
    "Rare",
    "Fire",
    3,
    2,
    "Permanent Ink",
    "Give your weakest other ally here +2 Hands and Protect.",
  ],
  [
    "og-skater",
    "OG Skater",
    "Rare",
    "Air",
    3,
    3,
    "Still Got It",
    "Move to your weakest other open district. If moved, gain +2 Hands.",
  ],
  [
    "inmate-kingpin",
    "Inmate Kingpin",
    "Legendary",
    "Dark",
    1,
    3,
    "Run the Yard",
    "Give every other friendly character here +1 Hand. Each Inmate gains +2 instead.",
  ],
  [
    "live-streamer-male",
    "Live Streamer — Male",
    "Rare",
    "Electric",
    2,
    2,
    "Raid the Chat",
    "Gain +1 Hand for each other friendly character here costing 2 or less, up to +2.",
  ],
  [
    "redneck",
    "Redneck",
    "Uncommon",
    "Earth",
    2,
    3,
    "Fix It Yourself",
    "Cleanse your weakest other ally here.",
  ],
  [
    "redneck-evil",
    "Redneck Evil",
    "Epic",
    "Fire",
    5,
    5,
    "Chain Reaction",
    "Give the strongest enemy here -2 Hands and 1 Burn.",
  ],
  [
    "lawyer",
    "Lawyer",
    "Rare",
    "Light",
    3,
    2,
    "Objection",
    "Cleanse your weakest other ally here and Protect it.",
  ],
  [
    "nigerian-father",
    "Nigerian Father",
    "Epic",
    "Earth",
    4,
    4,
    "High Expectations",
    "Give each other friendly character here with 3 or fewer Hands +2 Hands.",
  ],
  [
    "bouncer",
    "Bouncer",
    "Rare",
    "Earth",
    4,
    5,
    "Not on the List",
    "Move the weakest enemy here to its weakest other open district.",
  ],
  [
    "rent-a-cop",
    "Rent-a-Cop",
    "Uncommon",
    "Normal",
    2,
    2,
    "Mall Rules",
    "Lock the strongest enemy here against movement.",
  ],
] as const;

export const BLOCKBUSTERS = [
  [
    "the-shootout",
    "The Shootout",
    "Rare",
    "Fire",
    3,
    "Crossfire",
    "Hit every enemy here for 3 Hands; your strongest character here takes 1 damage.",
  ],
  [
    "the-block-spin",
    "The Block Spin",
    "Epic",
    "Dark",
    3,
    "Run It Back Twice",
    "Repeat every Hands reduction already dealt here this round three more times on surviving characters still here. Repeated damage cannot repeat itself.",
  ],
  [
    "the-sideshow",
    "The Sideshow",
    "Rare",
    "Air",
    2,
    "Clear the Intersection",
    "Move all characters from both sides out of this district into other legal districts. Each friendly character successfully moved gains +2 Hands. Locked cards stay.",
  ],
  [
    "the-concert",
    "The Concert",
    "Rare",
    "Electric",
    3,
    "Crowd Control",
    "Choose: give allies here +3 Hands and enemies +1; or hit enemies here for 3 and allies for 1.",
  ],
  [
    "the-setup",
    "The Setup",
    "Epic",
    "Dark",
    1,
    "Trust Nobody",
    "Sacrifice your weakest character here. Give your strongest other character here its current Hands plus 4 and Protection. Requires two allies.",
  ],
  [
    "the-dice-game",
    "The Dice Game",
    "Rare",
    "Normal",
    0,
    "Best Two of Three",
    "Wager 1–3 Motion (both sides must afford it). Each side rolls three D6; add the highest two. Winner takes the pot, up to 9 Motion, and gives their weakest local character +3 Hands. Ties refund both wagers.",
  ],
  [
    "the-after-party",
    "The After Party",
    "Epic",
    "Electric",
    2,
    "One More Round",
    "Extend this fight to 7 rounds and give every friendly character +2 Hands. Additional After Parties grant neither extension nor buffs.",
  ],
  [
    "the-kickback",
    "The Kickback",
    "Rare",
    "Air",
    2,
    "Everybody Pull Up",
    "Move all characters on both sides into this district. Each friendly character successfully moved gains +2 Hands. Locked cards and blocked destinations stay.",
  ],
  [
    "the-cookout",
    "The Cookout",
    "Epic",
    "Fire",
    3,
    "Hot Plate",
    "Serve three Soul Food cards in occupied friendly districts; each cleanses your weakest character there and grants +2 Hands. Leave one Burnt Plate: at this round end it gives a random friendly character there 1 Burn, then clears.",
  ],
  [
    "the-babyshower",
    "The Baby Shower",
    "Uncommon",
    "Light",
    2,
    "New Blessings",
    "Give every friendly character here +3 Hands, then draw up to two cards from your remaining deck.",
  ],
] as const;

const all = [...BLOCKBUSTER_CHARACTERS, ...BLOCKBUSTERS];
export const blockbusterWaveRarities: Record<string, CardRarity> =
  Object.fromEntries(all.map(([id, , rarity]) => [id, rarity]));
export const blockbusterWaveUpgradeEffects: Record<
  string,
  readonly AbilityUpgradeEffect[]
> = Object.fromEntries(
  all.map(([id]) => [
    id,
    [0, 1, 2].map(() => ({
      kind: "target-power" as const,
      amount: 1 as const,
      target: "friendly" as const,
      trigger: "base-success" as const,
    })),
  ]),
);
function growth(id: string, ability: string) {
  return [2, 5, 8].map((unlockLevel, index) => ({
    id: `${id}:upgrade:${index + 1}`,
    name: `${ability} ${["Practice", "Confidence", "Mastery"][index]}`,
    description:
      "After a successful base effect, your weakest character in the chosen lane gains +1 Hand.",
    unlockLevel,
    effect: blockbusterWaveUpgradeEffects[id][index],
  }));
}
export const blockbusterWaveCards: Record<string, Card> = {
  ...Object.fromEntries(
    BLOCKBUSTER_CHARACTERS.map(
      ([id, name, , type, cost, power, ability, effect]) => [
        id,
        {
          id,
          name,
          type,
          cost,
          power,
          ability,
          effect: `On Reveal: ${effect}`,
          kind: "character" as const,
          roles: ["Block Party"],
          abilityUpgrades: growth(id, ability),
        },
      ],
    ),
  ),
  ...Object.fromEntries(
    BLOCKBUSTERS.map(([id, name, , type, cost, ability, effect]) => [
      id,
      {
        id,
        name,
        type,
        cost,
        power: 0,
        ability,
        effect: `On Reveal: ${effect}`,
        kind: "blockbuster" as const,
        artworkLayout: "portrait" as const,
        roles: ["Lane Event"],
        abilityUpgrades: growth(id, ability),
      },
    ]),
  ),
};
