// Generated by scripts/import-character-cosmetics.mjs. Do not hand-edit.
export const CHARACTER_STYLE_ARTWORK: Record<string, { banner: string; deckCover: string; stickers: { id: string; name: string; image: string }[] }> = {
  "ashlee": {
    "banner": "assets/cosmetics/ashlee/banner-v3.webp",
    "deckCover": "assets/cosmetics/ashlee/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "ashlee:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/ashlee/sticker-portrait-v3.webp"
      },
      {
        "id": "ashlee:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/ashlee/sticker-action-v3.webp"
      },
      {
        "id": "ashlee:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/ashlee/sticker-reaction-v3.webp"
      },
      {
        "id": "ashlee:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/ashlee/sticker-emblem-v3.webp"
      }
    ]
  },
  "asphalt-apostle": {
    "banner": "assets/cosmetics/asphalt-apostle/banner-v3.webp",
    "deckCover": "assets/cosmetics/asphalt-apostle/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "asphalt-apostle:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/asphalt-apostle/sticker-portrait-v3.webp"
      },
      {
        "id": "asphalt-apostle:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/asphalt-apostle/sticker-action-v3.webp"
      },
      {
        "id": "asphalt-apostle:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/asphalt-apostle/sticker-reaction-v3.webp"
      },
      {
        "id": "asphalt-apostle:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/asphalt-apostle/sticker-emblem-v3.webp"
      }
    ]
  },
  "bbl-demon": {
    "banner": "assets/cosmetics/bbl-demon/banner-v3.webp",
    "deckCover": "assets/cosmetics/bbl-demon/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "bbl-demon:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/bbl-demon/sticker-portrait-v3.webp"
      },
      {
        "id": "bbl-demon:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/bbl-demon/sticker-action-v3.webp"
      },
      {
        "id": "bbl-demon:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/bbl-demon/sticker-reaction-v3.webp"
      },
      {
        "id": "bbl-demon:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/bbl-demon/sticker-emblem-v3.webp"
      }
    ]
  },
  "big-zoey": {
    "banner": "assets/cosmetics/big-zoey/banner-v3.webp",
    "deckCover": "assets/cosmetics/big-zoey/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "big-zoey:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/big-zoey/sticker-portrait-v3.webp"
      },
      {
        "id": "big-zoey:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/big-zoey/sticker-action-v3.webp"
      },
      {
        "id": "big-zoey:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/big-zoey/sticker-reaction-v3.webp"
      },
      {
        "id": "big-zoey:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/big-zoey/sticker-emblem-v3.webp"
      }
    ]
  },
  "black-cowboy": {
    "banner": "assets/cosmetics/black-cowboy/banner-v3.webp",
    "deckCover": "assets/cosmetics/black-cowboy/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "black-cowboy:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/black-cowboy/sticker-portrait-v3.webp"
      },
      {
        "id": "black-cowboy:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/black-cowboy/sticker-action-v3.webp"
      },
      {
        "id": "black-cowboy:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/black-cowboy/sticker-reaction-v3.webp"
      },
      {
        "id": "black-cowboy:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/black-cowboy/sticker-emblem-v3.webp"
      }
    ]
  },
  "block-party-titan": {
    "banner": "assets/cosmetics/block-party-titan/banner-v3.webp",
    "deckCover": "assets/cosmetics/block-party-titan/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "block-party-titan:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/block-party-titan/sticker-portrait-v3.webp"
      },
      {
        "id": "block-party-titan:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/block-party-titan/sticker-action-v3.webp"
      },
      {
        "id": "block-party-titan:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/block-party-titan/sticker-reaction-v3.webp"
      },
      {
        "id": "block-party-titan:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/block-party-titan/sticker-emblem-v3.webp"
      }
    ]
  },
  "buddy": {
    "banner": "assets/cosmetics/buddy/banner-v3.webp",
    "deckCover": "assets/cosmetics/buddy/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "buddy:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/buddy/sticker-portrait-v3.webp"
      },
      {
        "id": "buddy:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/buddy/sticker-action-v3.webp"
      },
      {
        "id": "buddy:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/buddy/sticker-reaction-v3.webp"
      },
      {
        "id": "buddy:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/buddy/sticker-emblem-v3.webp"
      }
    ]
  },
  "captain-jigga": {
    "banner": "assets/cosmetics/captain-jigga/banner-v3.webp",
    "deckCover": "assets/cosmetics/captain-jigga/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "captain-jigga:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/captain-jigga/sticker-portrait-v3.webp"
      },
      {
        "id": "captain-jigga:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/captain-jigga/sticker-action-v3.webp"
      },
      {
        "id": "captain-jigga:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/captain-jigga/sticker-reaction-v3.webp"
      },
      {
        "id": "captain-jigga:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/captain-jigga/sticker-emblem-v3.webp"
      }
    ]
  },
  "cheshire": {
    "banner": "assets/cosmetics/cheshire/banner-v3.webp",
    "deckCover": "assets/cosmetics/cheshire/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "cheshire:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/cheshire/sticker-portrait-v3.webp"
      },
      {
        "id": "cheshire:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/cheshire/sticker-action-v3.webp"
      },
      {
        "id": "cheshire:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/cheshire/sticker-reaction-v3.webp"
      },
      {
        "id": "cheshire:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/cheshire/sticker-emblem-v3.webp"
      }
    ]
  },
  "church-auntie": {
    "banner": "assets/cosmetics/church-auntie/banner-v3.webp",
    "deckCover": "assets/cosmetics/church-auntie/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "church-auntie:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/church-auntie/sticker-portrait-v3.webp"
      },
      {
        "id": "church-auntie:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/church-auntie/sticker-action-v3.webp"
      },
      {
        "id": "church-auntie:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/church-auntie/sticker-reaction-v3.webp"
      },
      {
        "id": "church-auntie:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/church-auntie/sticker-emblem-v3.webp"
      }
    ]
  },
  "cologne-criminal": {
    "banner": "assets/cosmetics/cologne-criminal/banner-v3.webp",
    "deckCover": "assets/cosmetics/cologne-criminal/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "cologne-criminal:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/cologne-criminal/sticker-portrait-v3.webp"
      },
      {
        "id": "cologne-criminal:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/cologne-criminal/sticker-action-v3.webp"
      },
      {
        "id": "cologne-criminal:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/cologne-criminal/sticker-reaction-v3.webp"
      },
      {
        "id": "cologne-criminal:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/cologne-criminal/sticker-emblem-v3.webp"
      }
    ]
  },
  "corrupt-pastor": {
    "banner": "assets/cosmetics/corrupt-pastor/banner-v3.webp",
    "deckCover": "assets/cosmetics/corrupt-pastor/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "corrupt-pastor:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/corrupt-pastor/sticker-portrait-v3.webp"
      },
      {
        "id": "corrupt-pastor:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/corrupt-pastor/sticker-action-v3.webp"
      },
      {
        "id": "corrupt-pastor:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/corrupt-pastor/sticker-reaction-v3.webp"
      },
      {
        "id": "corrupt-pastor:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/corrupt-pastor/sticker-emblem-v3.webp"
      }
    ]
  },
  "counter": {
    "banner": "assets/cosmetics/counter/banner-v3.webp",
    "deckCover": "assets/cosmetics/counter/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "counter:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/counter/sticker-portrait-v3.webp"
      },
      {
        "id": "counter:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/counter/sticker-action-v3.webp"
      },
      {
        "id": "counter:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/counter/sticker-reaction-v3.webp"
      },
      {
        "id": "counter:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/counter/sticker-emblem-v3.webp"
      }
    ]
  },
  "dorothy": {
    "banner": "assets/cosmetics/dorothy/banner-v3.webp",
    "deckCover": "assets/cosmetics/dorothy/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "dorothy:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/dorothy/sticker-portrait-v3.webp"
      },
      {
        "id": "dorothy:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/dorothy/sticker-action-v3.webp"
      },
      {
        "id": "dorothy:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/dorothy/sticker-reaction-v3.webp"
      },
      {
        "id": "dorothy:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/dorothy/sticker-emblem-v3.webp"
      }
    ]
  },
  "dr-fade": {
    "banner": "assets/cosmetics/dr-fade/banner-v3.webp",
    "deckCover": "assets/cosmetics/dr-fade/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "dr-fade:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/dr-fade/sticker-portrait-v3.webp"
      },
      {
        "id": "dr-fade:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/dr-fade/sticker-action-v3.webp"
      },
      {
        "id": "dr-fade:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/dr-fade/sticker-reaction-v3.webp"
      },
      {
        "id": "dr-fade:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/dr-fade/sticker-emblem-v3.webp"
      }
    ]
  },
  "dragonfly-jones": {
    "banner": "assets/cosmetics/dragonfly-jones/banner-v3.webp",
    "deckCover": "assets/cosmetics/dragonfly-jones/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "dragonfly-jones:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/dragonfly-jones/sticker-portrait-v3.webp"
      },
      {
        "id": "dragonfly-jones:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/dragonfly-jones/sticker-action-v3.webp"
      },
      {
        "id": "dragonfly-jones:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/dragonfly-jones/sticker-reaction-v3.webp"
      },
      {
        "id": "dragonfly-jones:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/dragonfly-jones/sticker-emblem-v3.webp"
      }
    ]
  },
  "folks": {
    "banner": "assets/cosmetics/folks/banner-v3.webp",
    "deckCover": "assets/cosmetics/folks/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "folks:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/folks/sticker-portrait-v3.webp"
      },
      {
        "id": "folks:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/folks/sticker-action-v3.webp"
      },
      {
        "id": "folks:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/folks/sticker-reaction-v3.webp"
      },
      {
        "id": "folks:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/folks/sticker-emblem-v3.webp"
      }
    ]
  },
  "foodz": {
    "banner": "assets/cosmetics/foodz/banner-v3.webp",
    "deckCover": "assets/cosmetics/foodz/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "foodz:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/foodz/sticker-portrait-v3.webp"
      },
      {
        "id": "foodz:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/foodz/sticker-action-v3.webp"
      },
      {
        "id": "foodz:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/foodz/sticker-reaction-v3.webp"
      },
      {
        "id": "foodz:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/foodz/sticker-emblem-v3.webp"
      }
    ]
  },
  "gamer": {
    "banner": "assets/cosmetics/gamer/banner-v3.webp",
    "deckCover": "assets/cosmetics/gamer/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "gamer:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/gamer/sticker-portrait-v3.webp"
      },
      {
        "id": "gamer:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/gamer/sticker-action-v3.webp"
      },
      {
        "id": "gamer:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/gamer/sticker-reaction-v3.webp"
      },
      {
        "id": "gamer:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/gamer/sticker-emblem-v3.webp"
      }
    ]
  },
  "god-of-hookah": {
    "banner": "assets/cosmetics/god-of-hookah/banner-v3.webp",
    "deckCover": "assets/cosmetics/god-of-hookah/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "god-of-hookah:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/god-of-hookah/sticker-portrait-v3.webp"
      },
      {
        "id": "god-of-hookah:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/god-of-hookah/sticker-action-v3.webp"
      },
      {
        "id": "god-of-hookah:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/god-of-hookah/sticker-reaction-v3.webp"
      },
      {
        "id": "god-of-hookah:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/god-of-hookah/sticker-emblem-v3.webp"
      }
    ]
  },
  "grown-man-fanboy": {
    "banner": "assets/cosmetics/grown-man-fanboy/banner-v3.webp",
    "deckCover": "assets/cosmetics/grown-man-fanboy/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "grown-man-fanboy:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/grown-man-fanboy/sticker-portrait-v3.webp"
      },
      {
        "id": "grown-man-fanboy:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/grown-man-fanboy/sticker-action-v3.webp"
      },
      {
        "id": "grown-man-fanboy:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/grown-man-fanboy/sticker-reaction-v3.webp"
      },
      {
        "id": "grown-man-fanboy:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/grown-man-fanboy/sticker-emblem-v3.webp"
      }
    ]
  },
  "guap": {
    "banner": "assets/cosmetics/guap/banner-v3.webp",
    "deckCover": "assets/cosmetics/guap/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "guap:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/guap/sticker-portrait-v3.webp"
      },
      {
        "id": "guap:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/guap/sticker-action-v3.webp"
      },
      {
        "id": "guap:v3-finnam",
        "name": "FINNAM!",
        "image": "assets/cosmetics/guap/sticker-finnam-v3.webp"
      },
      {
        "id": "guap:v3-falcon",
        "name": "Falcon",
        "image": "assets/cosmetics/guap/sticker-falcon-v3.webp"
      }
    ]
  },
  "homeless-guy": {
    "banner": "assets/cosmetics/homeless-guy/banner-v3.webp",
    "deckCover": "assets/cosmetics/homeless-guy/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "homeless-guy:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/homeless-guy/sticker-portrait-v3.webp"
      },
      {
        "id": "homeless-guy:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/homeless-guy/sticker-action-v3.webp"
      },
      {
        "id": "homeless-guy:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/homeless-guy/sticker-reaction-v3.webp"
      },
      {
        "id": "homeless-guy:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/homeless-guy/sticker-emblem-v3.webp"
      }
    ]
  },
  "homeless-legend": {
    "banner": "assets/cosmetics/homeless-legend/banner-v3.webp",
    "deckCover": "assets/cosmetics/homeless-legend/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "homeless-legend:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/homeless-legend/sticker-portrait-v3.webp"
      },
      {
        "id": "homeless-legend:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/homeless-legend/sticker-action-v3.webp"
      },
      {
        "id": "homeless-legend:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/homeless-legend/sticker-reaction-v3.webp"
      },
      {
        "id": "homeless-legend:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/homeless-legend/sticker-emblem-v3.webp"
      }
    ]
  },
  "homeless-wiseman": {
    "banner": "assets/cosmetics/homeless-wiseman/banner-v3.webp",
    "deckCover": "assets/cosmetics/homeless-wiseman/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "homeless-wiseman:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/homeless-wiseman/sticker-portrait-v3.webp"
      },
      {
        "id": "homeless-wiseman:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/homeless-wiseman/sticker-action-v3.webp"
      },
      {
        "id": "homeless-wiseman:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/homeless-wiseman/sticker-reaction-v3.webp"
      },
      {
        "id": "homeless-wiseman:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/homeless-wiseman/sticker-emblem-v3.webp"
      }
    ]
  },
  "john-henry": {
    "banner": "assets/cosmetics/john-henry/banner-v3.webp",
    "deckCover": "assets/cosmetics/john-henry/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "john-henry:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/john-henry/sticker-portrait-v3.webp"
      },
      {
        "id": "john-henry:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/john-henry/sticker-action-v3.webp"
      },
      {
        "id": "john-henry:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/john-henry/sticker-reaction-v3.webp"
      },
      {
        "id": "john-henry:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/john-henry/sticker-emblem-v3.webp"
      }
    ]
  },
  "juneteenth-chair-guy": {
    "banner": "assets/cosmetics/juneteenth-chair-guy/banner-v3.webp",
    "deckCover": "assets/cosmetics/juneteenth-chair-guy/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "juneteenth-chair-guy:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/juneteenth-chair-guy/sticker-portrait-v3.webp"
      },
      {
        "id": "juneteenth-chair-guy:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/juneteenth-chair-guy/sticker-action-v3.webp"
      },
      {
        "id": "juneteenth-chair-guy:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/juneteenth-chair-guy/sticker-reaction-v3.webp"
      },
      {
        "id": "juneteenth-chair-guy:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/juneteenth-chair-guy/sticker-emblem-v3.webp"
      }
    ]
  },
  "kyle": {
    "banner": "assets/cosmetics/kyle/banner-v3.webp",
    "deckCover": "assets/cosmetics/kyle/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "kyle:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/kyle/sticker-portrait-v3.webp"
      },
      {
        "id": "kyle:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/kyle/sticker-action-v3.webp"
      },
      {
        "id": "kyle:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/kyle/sticker-reaction-v3.webp"
      },
      {
        "id": "kyle:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/kyle/sticker-emblem-v3.webp"
      }
    ]
  },
  "landlord": {
    "banner": "assets/cosmetics/landlord/banner-v3.webp",
    "deckCover": "assets/cosmetics/landlord/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "landlord:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/landlord/sticker-portrait-v3.webp"
      },
      {
        "id": "landlord:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/landlord/sticker-action-v3.webp"
      },
      {
        "id": "landlord:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/landlord/sticker-reaction-v3.webp"
      },
      {
        "id": "landlord:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/landlord/sticker-emblem-v3.webp"
      }
    ]
  },
  "last-train-conductor": {
    "banner": "assets/cosmetics/last-train-conductor/banner-v3.webp",
    "deckCover": "assets/cosmetics/last-train-conductor/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "last-train-conductor:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/last-train-conductor/sticker-portrait-v3.webp"
      },
      {
        "id": "last-train-conductor:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/last-train-conductor/sticker-action-v3.webp"
      },
      {
        "id": "last-train-conductor:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/last-train-conductor/sticker-reaction-v3.webp"
      },
      {
        "id": "last-train-conductor:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/last-train-conductor/sticker-emblem-v3.webp"
      }
    ]
  },
  "leroy": {
    "banner": "assets/cosmetics/leroy/banner-v3.webp",
    "deckCover": "assets/cosmetics/leroy/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "leroy:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/leroy/sticker-portrait-v3.webp"
      },
      {
        "id": "leroy:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/leroy/sticker-action-v3.webp"
      },
      {
        "id": "leroy:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/leroy/sticker-reaction-v3.webp"
      },
      {
        "id": "leroy:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/leroy/sticker-emblem-v3.webp"
      }
    ]
  },
  "lion": {
    "banner": "assets/cosmetics/lion/banner-v3.webp",
    "deckCover": "assets/cosmetics/lion/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "lion:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/lion/sticker-portrait-v3.webp"
      },
      {
        "id": "lion:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/lion/sticker-action-v3.webp"
      },
      {
        "id": "lion:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/lion/sticker-reaction-v3.webp"
      },
      {
        "id": "lion:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/lion/sticker-emblem-v3.webp"
      }
    ]
  },
  "mansa-musa": {
    "banner": "assets/cosmetics/mansa-musa/banner-v3.webp",
    "deckCover": "assets/cosmetics/mansa-musa/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "mansa-musa:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/mansa-musa/sticker-portrait-v3.webp"
      },
      {
        "id": "mansa-musa:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/mansa-musa/sticker-action-v3.webp"
      },
      {
        "id": "mansa-musa:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/mansa-musa/sticker-reaction-v3.webp"
      },
      {
        "id": "mansa-musa:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/mansa-musa/sticker-emblem-v3.webp"
      }
    ]
  },
  "midnight-mayor": {
    "banner": "assets/cosmetics/midnight-mayor/banner-v3.webp",
    "deckCover": "assets/cosmetics/midnight-mayor/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "midnight-mayor:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/midnight-mayor/sticker-portrait-v3.webp"
      },
      {
        "id": "midnight-mayor:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/midnight-mayor/sticker-action-v3.webp"
      },
      {
        "id": "midnight-mayor:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/midnight-mayor/sticker-reaction-v3.webp"
      },
      {
        "id": "midnight-mayor:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/midnight-mayor/sticker-emblem-v3.webp"
      }
    ]
  },
  "night-shift-medic": {
    "banner": "assets/cosmetics/night-shift-medic/banner-v3.webp",
    "deckCover": "assets/cosmetics/night-shift-medic/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "night-shift-medic:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/night-shift-medic/sticker-portrait-v3.webp"
      },
      {
        "id": "night-shift-medic:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/night-shift-medic/sticker-action-v3.webp"
      },
      {
        "id": "night-shift-medic:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/night-shift-medic/sticker-reaction-v3.webp"
      },
      {
        "id": "night-shift-medic:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/night-shift-medic/sticker-emblem-v3.webp"
      }
    ]
  },
  "officer-oink": {
    "banner": "assets/cosmetics/officer-oink/banner-v3.webp",
    "deckCover": "assets/cosmetics/officer-oink/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "officer-oink:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/officer-oink/sticker-portrait-v3.webp"
      },
      {
        "id": "officer-oink:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/officer-oink/sticker-action-v3.webp"
      },
      {
        "id": "officer-oink:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/officer-oink/sticker-reaction-v3.webp"
      },
      {
        "id": "officer-oink:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/officer-oink/sticker-emblem-v3.webp"
      }
    ]
  },
  "og-uncle": {
    "banner": "assets/cosmetics/og-uncle/banner-v3.webp",
    "deckCover": "assets/cosmetics/og-uncle/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "og-uncle:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/og-uncle/sticker-portrait-v3.webp"
      },
      {
        "id": "og-uncle:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/og-uncle/sticker-action-v3.webp"
      },
      {
        "id": "og-uncle:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/og-uncle/sticker-reaction-v3.webp"
      },
      {
        "id": "og-uncle:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/og-uncle/sticker-emblem-v3.webp"
      }
    ]
  },
  "oz": {
    "banner": "assets/cosmetics/oz/banner-v3.webp",
    "deckCover": "assets/cosmetics/oz/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "oz:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/oz/sticker-portrait-v3.webp"
      },
      {
        "id": "oz:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/oz/sticker-action-v3.webp"
      },
      {
        "id": "oz:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/oz/sticker-reaction-v3.webp"
      },
      {
        "id": "oz:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/oz/sticker-emblem-v3.webp"
      }
    ]
  },
  "p-tang": {
    "banner": "assets/cosmetics/p-tang/banner-v3.webp",
    "deckCover": "assets/cosmetics/p-tang/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "p-tang:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/p-tang/sticker-portrait-v3.webp"
      },
      {
        "id": "p-tang:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/p-tang/sticker-action-v3.webp"
      },
      {
        "id": "p-tang:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/p-tang/sticker-reaction-v3.webp"
      },
      {
        "id": "p-tang:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/p-tang/sticker-emblem-v3.webp"
      }
    ]
  },
  "passport-bro": {
    "banner": "assets/cosmetics/passport-bro/banner-v3.webp",
    "deckCover": "assets/cosmetics/passport-bro/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "passport-bro:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/passport-bro/sticker-portrait-v3.webp"
      },
      {
        "id": "passport-bro:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/passport-bro/sticker-action-v3.webp"
      },
      {
        "id": "passport-bro:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/passport-bro/sticker-reaction-v3.webp"
      },
      {
        "id": "passport-bro:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/passport-bro/sticker-emblem-v3.webp"
      }
    ]
  },
  "pirate-radio-dj": {
    "banner": "assets/cosmetics/pirate-radio-dj/banner-v3.webp",
    "deckCover": "assets/cosmetics/pirate-radio-dj/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "pirate-radio-dj:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/pirate-radio-dj/sticker-portrait-v3.webp"
      },
      {
        "id": "pirate-radio-dj:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/pirate-radio-dj/sticker-action-v3.webp"
      },
      {
        "id": "pirate-radio-dj:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/pirate-radio-dj/sticker-reaction-v3.webp"
      },
      {
        "id": "pirate-radio-dj:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/pirate-radio-dj/sticker-emblem-v3.webp"
      }
    ]
  },
  "powerhouse": {
    "banner": "assets/cosmetics/powerhouse/banner-v3.webp",
    "deckCover": "assets/cosmetics/powerhouse/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "powerhouse:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/powerhouse/sticker-action-v3.webp"
      },
      {
        "id": "powerhouse:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/powerhouse/sticker-reaction-v3.webp"
      },
      {
        "id": "powerhouse:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/powerhouse/sticker-emblem-v3.webp"
      }
    ]
  },
  "promoter": {
    "banner": "assets/cosmetics/promoter/banner-v3.webp",
    "deckCover": "assets/cosmetics/promoter/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "promoter:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/promoter/sticker-portrait-v3.webp"
      },
      {
        "id": "promoter:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/promoter/sticker-action-v3.webp"
      },
      {
        "id": "promoter:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/promoter/sticker-reaction-v3.webp"
      },
      {
        "id": "promoter:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/promoter/sticker-emblem-v3.webp"
      }
    ]
  },
  "queen-of-hearts": {
    "banner": "assets/cosmetics/queen-of-hearts/banner-v3.webp",
    "deckCover": "assets/cosmetics/queen-of-hearts/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "queen-of-hearts:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/queen-of-hearts/sticker-portrait-v3.webp"
      },
      {
        "id": "queen-of-hearts:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/queen-of-hearts/sticker-action-v3.webp"
      },
      {
        "id": "queen-of-hearts:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/queen-of-hearts/sticker-reaction-v3.webp"
      },
      {
        "id": "queen-of-hearts:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/queen-of-hearts/sticker-emblem-v3.webp"
      }
    ]
  },
  "red-pill": {
    "banner": "assets/cosmetics/red-pill/banner-v3.webp",
    "deckCover": "assets/cosmetics/red-pill/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "red-pill:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/red-pill/sticker-portrait-v3.webp"
      },
      {
        "id": "red-pill:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/red-pill/sticker-action-v3.webp"
      },
      {
        "id": "red-pill:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/red-pill/sticker-reaction-v3.webp"
      },
      {
        "id": "red-pill:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/red-pill/sticker-emblem-v3.webp"
      }
    ]
  },
  "revolutionary-ronald": {
    "banner": "assets/cosmetics/revolutionary-ronald/banner-v3.webp",
    "deckCover": "assets/cosmetics/revolutionary-ronald/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "revolutionary-ronald:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/revolutionary-ronald/sticker-portrait-v3.webp"
      },
      {
        "id": "revolutionary-ronald:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/revolutionary-ronald/sticker-action-v3.webp"
      },
      {
        "id": "revolutionary-ronald:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/revolutionary-ronald/sticker-reaction-v3.webp"
      },
      {
        "id": "revolutionary-ronald:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/revolutionary-ronald/sticker-emblem-v3.webp"
      }
    ]
  },
  "seafood-assassin": {
    "banner": "assets/cosmetics/seafood-assassin/banner-v3.webp",
    "deckCover": "assets/cosmetics/seafood-assassin/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "seafood-assassin:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/seafood-assassin/sticker-portrait-v3.webp"
      },
      {
        "id": "seafood-assassin:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/seafood-assassin/sticker-action-v3.webp"
      },
      {
        "id": "seafood-assassin:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/seafood-assassin/sticker-reaction-v3.webp"
      },
      {
        "id": "seafood-assassin:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/seafood-assassin/sticker-emblem-v3.webp"
      }
    ]
  },
  "sherlock": {
    "banner": "assets/cosmetics/sherlock/banner-v3.webp",
    "deckCover": "assets/cosmetics/sherlock/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "sherlock:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/sherlock/sticker-portrait-v3.webp"
      },
      {
        "id": "sherlock:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/sherlock/sticker-action-v3.webp"
      },
      {
        "id": "sherlock:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/sherlock/sticker-reaction-v3.webp"
      },
      {
        "id": "sherlock:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/sherlock/sticker-emblem-v3.webp"
      }
    ]
  },
  "sho-nuff": {
    "banner": "assets/cosmetics/sho-nuff/banner-v3.webp",
    "deckCover": "assets/cosmetics/sho-nuff/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "sho-nuff:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/sho-nuff/sticker-portrait-v3.webp"
      },
      {
        "id": "sho-nuff:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/sho-nuff/sticker-action-v3.webp"
      },
      {
        "id": "sho-nuff:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/sho-nuff/sticker-reaction-v3.webp"
      },
      {
        "id": "sho-nuff:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/sho-nuff/sticker-emblem-v3.webp"
      }
    ]
  },
  "simmy": {
    "banner": "assets/cosmetics/simmy/banner-v3.webp",
    "deckCover": "assets/cosmetics/simmy/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "simmy:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/simmy/sticker-portrait-v3.webp"
      },
      {
        "id": "simmy:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/simmy/sticker-action-v3.webp"
      },
      {
        "id": "simmy:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/simmy/sticker-reaction-v3.webp"
      },
      {
        "id": "simmy:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/simmy/sticker-emblem-v3.webp"
      }
    ]
  },
  "sneaker-reseller": {
    "banner": "assets/cosmetics/sneaker-reseller/banner-v3.webp",
    "deckCover": "assets/cosmetics/sneaker-reseller/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "sneaker-reseller:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/sneaker-reseller/sticker-portrait-v3.webp"
      },
      {
        "id": "sneaker-reseller:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/sneaker-reseller/sticker-action-v3.webp"
      },
      {
        "id": "sneaker-reseller:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/sneaker-reseller/sticker-reaction-v3.webp"
      },
      {
        "id": "sneaker-reseller:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/sneaker-reseller/sticker-emblem-v3.webp"
      }
    ]
  },
  "sports-prodigy": {
    "banner": "assets/cosmetics/sports-prodigy/banner-v3.webp",
    "deckCover": "assets/cosmetics/sports-prodigy/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "sports-prodigy:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/sports-prodigy/sticker-portrait-v3.webp"
      },
      {
        "id": "sports-prodigy:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/sports-prodigy/sticker-action-v3.webp"
      },
      {
        "id": "sports-prodigy:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/sports-prodigy/sticker-reaction-v3.webp"
      },
      {
        "id": "sports-prodigy:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/sports-prodigy/sticker-emblem-v3.webp"
      }
    ]
  },
  "street-apostle": {
    "banner": "assets/cosmetics/street-apostle/banner-v3.webp",
    "deckCover": "assets/cosmetics/street-apostle/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "street-apostle:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/street-apostle/sticker-portrait-v3.webp"
      },
      {
        "id": "street-apostle:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/street-apostle/sticker-action-v3.webp"
      },
      {
        "id": "street-apostle:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/street-apostle/sticker-reaction-v3.webp"
      },
      {
        "id": "street-apostle:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/street-apostle/sticker-emblem-v3.webp"
      }
    ]
  },
  "techbro-rich": {
    "banner": "assets/cosmetics/techbro-rich/banner-v3.webp",
    "deckCover": "assets/cosmetics/techbro-rich/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "techbro-rich:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/techbro-rich/sticker-portrait-v3.webp"
      },
      {
        "id": "techbro-rich:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/techbro-rich/sticker-action-v3.webp"
      },
      {
        "id": "techbro-rich:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/techbro-rich/sticker-reaction-v3.webp"
      },
      {
        "id": "techbro-rich:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/techbro-rich/sticker-emblem-v3.webp"
      }
    ]
  },
  "the-feds": {
    "banner": "assets/cosmetics/the-feds/banner-v3.webp",
    "deckCover": "assets/cosmetics/the-feds/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "the-feds:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/the-feds/sticker-portrait-v3.webp"
      },
      {
        "id": "the-feds:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/the-feds/sticker-action-v3.webp"
      },
      {
        "id": "the-feds:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/the-feds/sticker-reaction-v3.webp"
      },
      {
        "id": "the-feds:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/the-feds/sticker-emblem-v3.webp"
      }
    ]
  },
  "the-mailman": {
    "banner": "assets/cosmetics/the-mailman/banner-v3.webp",
    "deckCover": "assets/cosmetics/the-mailman/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "the-mailman:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/the-mailman/sticker-portrait-v3.webp"
      },
      {
        "id": "the-mailman:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/the-mailman/sticker-action-v3.webp"
      },
      {
        "id": "the-mailman:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/the-mailman/sticker-reaction-v3.webp"
      },
      {
        "id": "the-mailman:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/the-mailman/sticker-emblem-v3.webp"
      }
    ]
  },
  "trap-vamp": {
    "banner": "assets/cosmetics/trap-vamp/banner-v3.webp",
    "deckCover": "assets/cosmetics/trap-vamp/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "trap-vamp:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/trap-vamp/sticker-portrait-v3.webp"
      },
      {
        "id": "trap-vamp:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/trap-vamp/sticker-action-v3.webp"
      },
      {
        "id": "trap-vamp:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/trap-vamp/sticker-reaction-v3.webp"
      },
      {
        "id": "trap-vamp:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/trap-vamp/sticker-emblem-v3.webp"
      }
    ]
  },
  "tron": {
    "banner": "assets/cosmetics/tron/banner-v3.webp",
    "deckCover": "assets/cosmetics/tron/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "tron:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/tron/sticker-portrait-v3.webp"
      },
      {
        "id": "tron:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/tron/sticker-action-v3.webp"
      },
      {
        "id": "tron:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/tron/sticker-reaction-v3.webp"
      },
      {
        "id": "tron:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/tron/sticker-emblem-v3.webp"
      }
    ]
  },
  "yasuke": {
    "banner": "assets/cosmetics/yasuke/banner-v3.webp",
    "deckCover": "assets/cosmetics/yasuke/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "yasuke:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/yasuke/sticker-portrait-v3.webp"
      },
      {
        "id": "yasuke:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/yasuke/sticker-action-v3.webp"
      },
      {
        "id": "yasuke:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/yasuke/sticker-reaction-v3.webp"
      },
      {
        "id": "yasuke:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/yasuke/sticker-emblem-v3.webp"
      }
    ]
  },
  "yn-atv-lord": {
    "banner": "assets/cosmetics/yn-atv-lord/banner-v3.webp",
    "deckCover": "assets/cosmetics/yn-atv-lord/deck-cover-v3.webp",
    "stickers": [
      {
        "id": "yn-atv-lord:v3-portrait",
        "name": "Portrait",
        "image": "assets/cosmetics/yn-atv-lord/sticker-portrait-v3.webp"
      },
      {
        "id": "yn-atv-lord:v3-action",
        "name": "Action",
        "image": "assets/cosmetics/yn-atv-lord/sticker-action-v3.webp"
      },
      {
        "id": "yn-atv-lord:v3-reaction",
        "name": "Reaction",
        "image": "assets/cosmetics/yn-atv-lord/sticker-reaction-v3.webp"
      },
      {
        "id": "yn-atv-lord:v3-emblem",
        "name": "Emblem",
        "image": "assets/cosmetics/yn-atv-lord/sticker-emblem-v3.webp"
      }
    ]
  }
};
