import { SELECTED_FITNESS_IDS, SELECTED_MUSIC_IDS } from './selectedWave';
import type { AbilityUpgradeEffect, Card, CardRarity } from './data';

/** Canonical IDs are shared by collection, combat, art and saved progression. */
export const MUSIC_INDUSTRY_WAVE = [
  ['the-opening-act', 'The Opening Act', 'Common', 'Air', 1, 2, 'Soundcheck', 'On Reveal: Prepare your weakest other unlocked district through next round. Your next different Music character played there refunds 1 Motion after a successful entrance. One pending Soundcheck per side; one refund per side per match.', 'Combo'],
  ['the-dj', 'The DJ', 'Rare', 'Electric', 2, 3, 'Spinback', 'On Reveal: Return your weakest other movable Music character here costing 3 or less to hand. Its next deployment costs 1 less Motion, minimum 1, through next round. One successful Spinback per side per match; returning never resets limits.', 'Return'],
  ['the-hype-man', 'The Hype Man', 'Uncommon', 'Air', 2, 3, 'Say It Back', 'On Reveal: Call your weakest other Music ally anywhere through next round. Your next different Music character played in another district gives the caller and responder +1 Hand each and Protects the caller. One Call per side; caller and Hype Man must remain active.', 'Combo'],
  ['the-manager-nice', 'The Manager — Nice', 'Rare', 'Light', 2, 3, 'Read the Contract', 'On Reveal: Insure your next other Music deployment through next round. If its entrance is canceled or queued by an enemy, refund 1 Motion once; otherwise Protect it after its entrance. That deployment spends the rider either way. One rider per side.', 'Protection'],
  ['the-rapper', 'The Rapper', 'Rare', 'Fire', 3, 4, 'Sixteen Bars', 'Ongoing: Once per round, a different Music ally successfully resolving an entrance here makes Rapper hit the strongest local enemy for 1. Separately once per round, a successful Music entrance elsewhere gives the weakest ally there +1 Hand. Echoes do not count; copies share both limits.', 'Pressure'],
  ['the-janky-promoter', 'The Janky Promoter', 'Rare', 'Dark', 3, 3, 'Wrong Address', 'On Reveal: Post a public bogus booking in the enemy’s weakest other unlocked district through next round. Their next character played or moved there takes 1 damage; only if damage lands, it is Weakened. The trap is spent even if blocked. One booking per side.', 'Trap'],
  ['the-local-celebrity', 'The Local Celebrity', 'Rare', 'Air', 3, 4, 'Everybody Watching', 'Ongoing: Once per round, after an enemy actually damages a different friendly Music character in another district, move Celebrity there if legal. Gain +1 Hand only if the move succeeds. Copies share the trigger; blocked hits and friendly damage do not count.', 'Movement'],
  ['the-battle-rapper', 'The Battle Rapper', 'Epic', 'Poison', 3, 4, 'Diss Track', 'On Reveal: Trim up to 2 bonus Hands from the strongest enemy here; if it has no bonus, hit it for 2 instead. If this changes the target, mark it through next round: its next positive Hands gain causes one Silence attempt. That gain remains. Protection and immunity apply.', 'Disruption'],
  ['the-manager-evil', 'The Manager — Evil', 'Epic', 'Dark', 4, 5, '360 Deal', 'On Reveal: Give your strongest other local Music ally +3 Hands and prevent its movement through next round. At expiry, transfer up to 2 remaining bonus Hands to an active surviving Evil Manager. Cleansing cancels the contract without clearing other Locks. One contract per side; each client signs once per match.', 'Investment'],
  ['the-og-rap-legend', 'The OG Rap Legend', 'Legendary', 'Light', 5, 6, 'Pass the Torch', 'On Reveal: Repeat the weakest other active Music ally’s successful entrance, printed cost 3 or less, at its current district, then Protect it. Give the weakest Music ally in each other district +1 Hand. One Torch per side per match; once-only limits stay spent and passives are never repeated.', 'Finisher'],
  ['fitness-bro', 'Fitness Bro', 'Uncommon', 'Normal', 3, 4, 'One More Rep', 'Ongoing: At round end, if you played another character in a different district this round, gain +2 Hands and record one Rep. At three Reps, gain Protection and stop. One Rep per round, up to three per match; copies share progress. Supports, tokens and echoes do not count.', 'Growth'],
  ['fitness-girl', 'Fitness Girl', 'Uncommon', 'Water', 2, 3, 'Active Recovery', 'On Reveal: Move to your weakest other open district. After a successful move, restore up to 2 actual damage and remove Burn from your weakest injured other ally there. If nobody is injured, remove Burn from your weakest burning other ally there instead. If nobody needs either recovery, give your weakest other ally there +1 Hand instead. A failed move gives no recovery or bonus.', 'Sustain'],
  ['personal-trainer', 'Personal Trainer', 'Rare', 'Normal', 3, 4, 'Circuit Training', 'On Reveal: Train your weakest other ally here through the next two rounds. Its first successful move out gains +2 Hands. Its first later visit to the remaining third district gains +2 Hands and Protection. One circuit per side; each character can train once per match. Moving between only two districts never finishes.', 'Movement'],
  ['demon-trainer', 'Demon Trainer', 'Epic', 'Fire', 4, 5, 'No Days Off', 'Ongoing: The first other friendly Fitness character destroyed by an enemy each round gives Demon +2 Hands and hits the strongest enemy in the fallen athlete’s district for 1. At most two payouts per side per match. Demon must already be active; sacrifices, tokens and friendly damage never count.', 'Comeback'],
] as const;

export const MUSIC_INDUSTRY_IDS = MUSIC_INDUSTRY_WAVE.slice(0, 10).map(([id]) => id);
export const FITNESS_WAVE_IDS = MUSIC_INDUSTRY_WAVE.slice(10).map(([id]) => id);
export const MUSIC_CHARACTER_IDS: readonly string[] = [...MUSIC_INDUSTRY_IDS, ...SELECTED_MUSIC_IDS, 'failedrapper', 'busker', 'piratedj', 'promoter'];
export const FITNESS_CHARACTER_IDS: readonly string[] = [...FITNESS_WAVE_IDS, ...SELECTED_FITNESS_IDS, 'failedathlete', 'sportsprodigy', 'hooper'];
export const musicIndustryRarities: Record<string, CardRarity> = Object.fromEntries(MUSIC_INDUSTRY_WAVE.map(([id, , rarity]) => [id, rarity]));
export const musicIndustryFactions: Record<string, string> = Object.fromEntries(MUSIC_INDUSTRY_WAVE.map(([id], index) => [id, index < 10 ? 'Music Industry' : 'Fitness']));
export const musicIndustryUpgradeEffects: Record<string, readonly AbilityUpgradeEffect[]> = Object.fromEntries(MUSIC_INDUSTRY_WAVE.map(([id]) => [id, [0, 1, 2].map(() => ({ kind: 'self-power' as const, amount: 1 as const, trigger: 'base-success' as const }))]));
export const musicIndustryWaveCards: Record<string, Card> = Object.fromEntries(MUSIC_INDUSTRY_WAVE.map(([id, name, , type, cost, power, ability, effect, role]) => [id, {
  id, name, type, cost, power, ability, effect, kind: 'character' as const, artworkLayout: 'portrait', roles: [role],
  portraitAccent: type === 'Poison' ? '#b78aff' : type === 'Light' ? '#ffe09a' : type === 'Water' ? '#74cfff' : type === 'Electric' ? '#69e7f2' : type === 'Fire' ? '#ff825a' : '#e9c56f',
  abilityUpgrades: [2, 5, 8].map((unlockLevel, index) => ({ id: `${id}:upgrade:${index + 1}`, name: `${ability} ${['Practice', 'Confidence', 'Mastery'][index]}`, description: 'The first time the base ability succeeds this match, gain +1 Hand.', unlockLevel, effect: musicIndustryUpgradeEffects[id][index] })),
}]));
