import type { Card, CardRarity, AbilityUpgradeEffect } from './data';
export const SELECTED_WAVE = [
  [
    'track-suit-auntie',
    'Track Suit Auntie',
    'Common',
    'Normal',
    1,
    1,
    'First Lap',
    'On Reveal: Move to your weakest legal other district.',
    'Fitness',
    'Movement',
  ],
  [
    'gym-bag-yn',
    'Gym Bag YN',
    'Uncommon',
    'Dark',
    2,
    2,
    'Bag Check',
    'On Reveal: Move your weakest other local Fitness ally to your weakest legal other district. One successful Bag Check per side per round.',
    'Fitness',
    'Movement',
  ],
  [
    'stairwell-sprinter',
    'Stairwell Sprinter',
    'Common',
    'Air',
    2,
    2,
    'Take the Stairs',
    'On Reveal: Move to an unvisited legal district. Gain +1 Hand after arrival once per instance per match.',
    'Fitness',
    'Movement',
  ],
  [
    'last-set-og',
    'Last Set OG',
    'Rare',
    'Fire',
    4,
    4,
    'Finish the Circuit',
    'On Reveal: If a friendly Fitness character has visited all three districts, give your weakest Fitness ally in each occupied district +1 Hand. Otherwise Protect your weakest other local Fitness ally. One circuit finish per side per match.',
    'Fitness',
    'Support',
  ],
  [
    'tour-van-driver',
    'Tour Van Driver',
    'Uncommon',
    'Earth',
    3,
    3,
    'Next Stop',
    'On Reveal: Bring your weakest movable Music ally from another district here. Both gain +1 Hand after arrival. Once per side per round.',
    'Music Industry',
    'Movement',
  ],
  [
    'mixtape-cousin',
    'Mixtape Cousin',
    'Common',
    'Air',
    2,
    2,
    'Second Stage',
    'On Reveal: Move your weakest other local Music ally to your weakest legal other district.',
    'Music Industry',
    'Movement',
  ],
  [
    'merch-table-hustler',
    'Merch Table Hustler',
    'Rare',
    'Electric',
    3,
    3,
    'Tour Money',
    'Ongoing: The first different Music character successfully resolving an entrance here each round earns one local Music discount of 1 Motion through that round, minimum 1. Two discounts per side per match. Echoes do not count.',
    'Music Industry',
    'Tempo',
  ],
  [
    'the-favorite-grandchild',
    'The Favorite Grandchild',
    'Common',
    'Fire',
    1,
    2,
    'Everybody Loves Me',
    'On Reveal: Move to your weakest legal other district.',
    'Family',
    'Movement',
  ],
  [
    'cousin-back-from-college',
    'Cousin Back From College',
    'Common',
    'Fire',
    2,
    3,
    'Back on the Block',
    'On Reveal: Move your weakest other local Fire or Family ally to your weakest legal other district.',
    'Family',
    'Movement',
  ],
  [
    'plate-auntie',
    'Plate Auntie',
    'Uncommon',
    'Fire',
    2,
    3,
    'Fix You a Plate',
    'On Reveal: Recover up to 2 lost Hands and remove Burn from your weakest injured other local Fire or Family ally. If nobody is injured, remove one eligible ally’s Burn; if nobody needs either, give your weakest eligible ally +1 Hand instead.',
    'Family',
    'Sustain',
  ],
  [
    'church-aunties-rival',
    'Church Auntie’s Rival',
    'Common',
    'Fire',
    2,
    3,
    'Not My Baby',
    'On Reveal: Protect your weakest other local Fire or Family ally.',
    'Family',
    'Protection',
  ],
  [
    'big-sister',
    'Big Sister',
    'Uncommon',
    'Fire',
    3,
    4,
    'Everybody Inside',
    'Ongoing: The first different Fire or Family ally moving here each round gains +1 Hand. Three payouts per side per match.',
    'Family',
    'Support',
  ],
  [
    'second-plate-cousin',
    'Second Plate Cousin',
    'Uncommon',
    'Fire',
    3,
    4,
    'Save Me Some',
    'Ongoing: When another local Fire or Family ally genuinely gains Hands, gain +1 Hand. Once per round, three payouts per side per match. Copied gains cannot trigger sharing.',
    'Family',
    'Growth',
  ],
  [
    'grill-uncle',
    'Grill Uncle',
    'Rare',
    'Fire',
    3,
    4,
    'Still Hot',
    'On Reveal: Apply 1 Burn to the strongest enemy here. Ongoing: Actual enemy Burn damage here grants +1 Hand once per round, twice per side per match.',
    'Family',
    'Disruption',
  ],
  [
    'grandma-said-sit-down',
    'Grandma Said Sit Down',
    'Rare',
    'Fire',
    4,
    5,
    'Dinner’s Ready',
    'On Reveal: Hit the strongest enemy here for 1 Hand, or 2 if two distinct friendly characters moved this round. One successful entrance per instance per match.',
    'Family',
    'Pressure',
  ],
  [
    'gym-spotter-yn',
    'Gym Spotter YN',
    'Common',
    'Normal',
    2,
    3,
    'I Got You',
    'On Reveal: Protect your weakest other local Fitness ally. If it successfully moves this round, it gains +1 Hand once.',
    'Fitness',
    'Protection',
  ],
  [
    'calisthenics-yn',
    'Calisthenics YN',
    'Uncommon',
    'Earth',
    2,
    3,
    'Bodyweight',
    'Ongoing: Your first successful move each round gains +1 Hand. Two payouts per instance per match.',
    'Fitness',
    'Growth',
  ],
  [
    'og-calisthenics',
    'OG Calisthenics',
    'Rare',
    'Earth',
    4,
    5,
    'No Equipment Needed',
    'On Reveal: If Fitness allies occupy all three districts, give your weakest Fitness ally in each district +1 Hand. Otherwise give your weakest other local Fitness ally +1 Hand and Protection. Once per side per match.',
    'Fitness',
    'Support',
  ],
  [
    'night-bus-driver',
    'Night Bus Driver',
    'Common',
    'Dark',
    2,
    3,
    'Last Bus',
    'On Reveal: Bring your weakest movable ally from another district here if there is space.',
    'Around the Block',
    'Movement',
  ],
  [
    'community-cook',
    'Community Cook',
    'Uncommon',
    'Plant',
    2,
    3,
    'Everybody Eats',
    'On Reveal: Recover up to 2 lost Hands on your weakest injured other ally here; otherwise give your weakest other ally here +1 Hand. A Homeless recipient also gains Protection. One meal per recipient per match.',
    'Community',
    'Sustain',
  ],
  [
    'jump-rope-menace',
    'Jump Rope Menace',
    'Uncommon',
    'Electric',
    3,
    4,
    'Double Dutch',
    'Ongoing: After two distinct Fitness allies successfully move in the same round, gain +2 Hands. One payout per side per round, twice per match.',
    'Fitness',
    'Growth',
  ],
  [
    'delivery-app-cyclist',
    'Delivery App Cyclist',
    'Common',
    'Electric',
    2,
    3,
    'Contactless',
    'On Reveal: Move to your weakest legal other district. Give your weakest other ally there +1 Hand after arrival, once per instance per match.',
    'Around the Block',
    'Movement',
  ],
  [
    'studio-couch-yn',
    'Studio Couch YN',
    'Common',
    'Air',
    1,
    2,
    'Wake Up Bro',
    'On Reveal: Give your weakest other local Music ally +1 Hand.',
    'Music Industry',
    'Support',
  ],
  [
    'barbershop-heckler',
    'Barbershop Heckler',
    'Uncommon',
    'Air',
    2,
    3,
    'That Ain’t It',
    'On Reveal: Trim up to 2 bonus Hands from the strongest enemy here. If any bonus was removed, your weakest other ally here gains +1 Hand.',
    'The Cypher',
    'Disruption',
  ],
  [
    'group-chat-instigator',
    'Group Chat Instigator',
    'Rare',
    'Air',
    3,
    4,
    'Come Outside',
    'On Reveal: Hit the strongest enemy here for 1 Hand. If damage lands and two different friendly characters moved this round, hit the strongest enemy in another district for 1.',
    'The Cypher',
    'Pressure',
  ],
  [
    'bluetooth-unc',
    'Bluetooth Unc',
    'Common',
    'Air',
    2,
    3,
    'You Hear Me',
    'On Reveal: Remove Silence from your weakest silenced other ally here. If none is silenced, Protect your weakest other ally here instead.',
    'Around the Block',
    'Protection',
  ],
  [
    'one-man-band',
    'One-Man Band',
    'Rare',
    'Electric',
    4,
    5,
    'Whole Set',
    'On Reveal: If Music allies occupy all three districts, give your weakest Music ally in each district +1 Hand; otherwise give your weakest other local Music ally +2 Hands. Once per side per match.',
    'Music Industry',
    'Support',
  ],
  [
    'booster',
    'Booster',
    'Uncommon',
    'Dark',
    2,
    3,
    'Five Finger Discount',
    'On Reveal: Trim up to 1 bonus Hand from the strongest enemy here and gain that amount. One successful steal per instance per match.',
    'Around the Block',
    'Disruption',
  ],
  [
    'indian-scammer',
    'Indian Scammer',
    'Uncommon',
    'Dark',
    3,
    4,
    'Refund Department',
    'On Reveal: Trim up to 2 bonus Hands from the strongest enemy here. If bonus Hands were removed, give your weakest other local ally +1 Hand and Protection. Once per instance per match.',
    'Around the Block',
    'Disruption',
  ],
  [
    'naija-scammer',
    'Naija Scammer',
    'Rare',
    'Dark',
    3,
    4,
    'Till Debt Do Us Part',
    'On Reveal: Summon a 0-Motion / 1-Hand Fake Marriage token here if there is space, then Protect your weakest other character here. One summon per side per match. The token earns +1 Hand when a different ally moves here, once per round, twice per match.',
    'Around the Block',
    'Token',
  ],
  [
    'black-air-fade-1s',
    'Black Air Fade 1’s',
    'Uncommon',
    'Dark',
    1,
    0,
    'Bad Intentions',
    'On Reveal: Give your weakest other character here +1 Hand and Protection. Its next successful move this round grants +1 Hand once. One fitting per target per match.',
    'Everyday Essentials',
    'Support',
  ],
] as const;
export const selectedCards: Record<string, Card> = Object.fromEntries(
  SELECTED_WAVE.map(
    ([id, name, , type, cost, power, ability, effect, , role]) => [
      id,
      {
        id,
        name,
        type,
        cost,
        power,
        ability,
        effect,
        kind: id === 'black-air-fade-1s' ? 'support' : 'character',
        roles: [role],
        ...(id === 'og-calisthenics' ? { artworkLayout: 'portrait' as const } : {}),
        abilityUpgrades: [2, 5, 8].map((unlockLevel, index) => ({
          id: `${id}:upgrade:${index + 1}`,
          name: `${ability} ${['Practice', 'Confidence', 'Mastery'][index]}`,
          description:
            'The first successful base ability this match grants +1 Hand.',
          unlockLevel,
          effect: {
            kind: 'self-power' as const,
            amount: 1 as const,
            trigger: 'base-success' as const,
          },
        })),
      },
    ],
  ),
);
export const selectedRarities: Record<string, CardRarity> = Object.fromEntries(
  SELECTED_WAVE.map(([id, , rarity]) => [id, rarity]),
);
export const selectedFactions: Record<string, string> = Object.fromEntries(
  SELECTED_WAVE.map(([id, , , , , , , , faction]) => [id, faction]),
);
export const selectedUpgradeEffects: Record<
  string,
  readonly AbilityUpgradeEffect[]
> = Object.fromEntries(
  Object.entries(selectedCards).map(([id, c]) => [
    id,
    c.abilityUpgrades.map((u) => u.effect!),
  ]),
);
export const FAMILY_IDS = SELECTED_WAVE.filter(
  (row) => row[8] === 'Family',
).map((row) => row[0]) as readonly string[];
export const SELECTED_FITNESS_IDS = SELECTED_WAVE.filter(
  (row) => row[8] === 'Fitness',
).map((row) => row[0]) as readonly string[];
export const SELECTED_MUSIC_IDS = SELECTED_WAVE.filter(
  (row) => row[8] === 'Music Industry',
).map((row) => row[0]) as readonly string[];
export const fakeMarriage: Card = {
  id: 'fake-marriage',
  name: 'Fake Marriage',
  type: 'Dark',
  cost: 0,
  power: 1,
  kind: 'token',
  ability: 'Shared Account',
  effect:
    'The first different friendly character moving here each round grants +1 Hand, twice per match. Summoned only.',
  abilityUpgrades: [],
};
