import type { StoryChapter } from "./story";

/** Authored locations keyed by stable node ID; no gameplay or reward changes. */
export const STORY_ENVIRONMENTS: Readonly<Record<string, string>> = {
  "s2-the-morning-after-opening": "33-the-morning-after-rooftop",
  "s2-rooftop-demo-table": "33-the-morning-after-rooftop",
  "s2-the-morning-after-evidence": "33-the-morning-after-rooftop",
  "s2-launch-crew-scrimmage": "33-the-morning-after-rooftop",
  "s2-first-night-watch": "33-the-morning-after-rooftop",
  "s2-the-morning-after-closing": "33-the-morning-after-rooftop",
  "s2-the-rent-party-opening": "34-rent-party-courtyard",
  "s2-fish-fry-fade": "34-rent-party-courtyard",
  "s2-auction-interruption": "34-rent-party-courtyard",
  "s2-pledge-drive-final": "34-rent-party-courtyard",
  "s2-the-rent-party-closing": "34-rent-party-courtyard",
  "s2-unlicensed-improvements-opening": "35-community-space-under-repair",
  "s2-tool-cage-rules": "35-community-space-under-repair",
  "s2-paint-line-challenge": "35-community-space-under-repair",
  "s2-rail-inspection": "35-community-space-under-repair",
  "s2-unlicensed-improvements-closing": "35-community-space-under-repair",
  "s2-regular-guy-behavior-opening": "35-community-space-under-repair",
  "s2-regular-guy-open": "35-community-space-under-repair",
  "s2-news-van-scramble": "35-community-space-under-repair",
  "s2-noise-complaint-main-event": "35-community-space-under-repair",
  "s2-regular-guy-behavior-closing": "35-community-space-under-repair",
  "s2-museum-of-the-block-opening": "36-museum-of-the-block",
  "s2-label-maker-war": "36-museum-of-the-block",
  "s2-museum-of-the-block-evidence": "36-museum-of-the-block",
  "s2-memory-booth": "36-museum-of-the-block",
  "s2-curators-table": "36-museum-of-the-block",
  "s2-museum-of-the-block-closing": "36-museum-of-the-block",
  "s2-everybody-has-a-buyer-opening": "36-museum-of-the-block",
  "s2-buyer-pitch-off": "36-museum-of-the-block",
  "s2-coop-chair-challenge": "36-museum-of-the-block",
  "s2-richs-option": "36-museum-of-the-block",
  "s2-everybody-has-a-buyer-closing": "36-museum-of-the-block",
  "s2-premiere-night-opening": "37-premiere-night-entrance",
  "s2-overflow-open": "37-premiere-night-entrance",
  "s2-premiere-night-evidence": "37-premiere-night-entrance",
  "s2-courier-cut-through": "37-premiere-night-entrance",
  "s2-premiere-main-event": "37-premiere-night-entrance",
  "s2-premiere-night-closing": "37-premiere-night-entrance",
  "s2-the-blockbuster-opening": "37-premiere-night-entrance",
  "s2-teardown-dash": "37-premiere-night-entrance",
  "s2-community-exhibition": "38-the-saved-gathering-place",
  "s2-blockbuster-final": "38-the-saved-gathering-place",
  "s2-the-blockbuster-closing": "38-the-saved-gathering-place",
  "sherlock-cold-projector": "01-after-hours-block-party",
  "sherlock-test-the-witness": "01-after-hours-block-party",
  "sherlock-alices-alibi-maze": "01-after-hours-block-party",
  "sherlock-three-bad-alibis": "03-promoters-back-office",
  "sherlock-prop-room-inventory": "02-bootleg-film-archive",
  "sherlock-snitchs-exclusive": "03-promoters-back-office",
  "sherlock-evidence-order": "02-bootleg-film-archive",
  "sherlock-false-bottom-fade": "02-bootleg-film-archive",
  "sherlock-reel-in-the-trophy": "02-bootleg-film-archive",
  "sherlock-impossible-date": "03-promoters-back-office",
  "sherlock-cornballs-reconstruction": "02-bootleg-film-archive",
  "sherlock-final-deduction": "03-promoters-back-office",
  "sherlock-the-missing-motion": "01-after-hours-block-party",
  "sherlock-curtain-call": "01-after-hours-block-party",
  "sherlock-thirteenth-bell-ticket": "04-impossible-midnight-station",
  "sherlock-thirteenth-bell-platform": "04-impossible-midnight-station",
  "sherlock-thirteenth-bell-clocks": "04-impossible-midnight-station",
  "sherlock-thirteenth-bell-guard": "06-lost-luggage-cage",
  "sherlock-thirteenth-bell-route": "05-railway-loading-alley",
  "sherlock-thirteenth-bell-interview": "06-lost-luggage-cage",
  "sherlock-thirteenth-bell-bell": "04-impossible-midnight-station",
  "sherlock-thirteenth-bell-receipt": "05-railway-loading-alley",
  "sherlock-thirteenth-bell-return": "05-railway-loading-alley",
  "sherlock-dead-air-voice": "07-community-radio-booth",
  "sherlock-dead-air-tape": "07-community-radio-booth",
  "sherlock-dead-air-soundcheck": "07-community-radio-booth",
  "sherlock-dead-air-switches": "08-transmitter-cupboard",
  "sherlock-dead-air-archive": "08-transmitter-cupboard",
  "sherlock-dead-air-voices": "07-community-radio-booth",
  "sherlock-dead-air-meeting": "09-radio-rooftop",
  "sherlock-dead-air-airtime": "09-radio-rooftop",
  "sherlock-dead-air-signoff": "07-community-radio-booth",
  "sherlock-negative-space-display": "10-neighborhood-trophy-gallery",
  "sherlock-negative-space-seats": "10-neighborhood-trophy-gallery",
  "sherlock-negative-space-reflection": "10-neighborhood-trophy-gallery",
  "sherlock-negative-space-ledger": "11-gallery-maintenance-corridor",
  "sherlock-negative-space-promoter": "03-promoters-back-office",
  "sherlock-negative-space-proof": "11-gallery-maintenance-corridor",
  "sherlock-negative-space-final": "10-neighborhood-trophy-gallery",
  "sherlock-negative-space-repair": "10-neighborhood-trophy-gallery",
  "sherlock-negative-space-casebook": "03-promoters-back-office",
  "oz-yellow-line-storm": "12-yellow-line-bus-terminal",
  "oz-yellow-line-map": "12-yellow-line-bus-terminal",
  "oz-yellow-line-straw": "12-yellow-line-bus-terminal",
  "oz-yellow-line-bridge": "13-sponsored-toll-bridge",
  "oz-yellow-line-heart": "13-sponsored-toll-bridge",
  "oz-yellow-line-courage": "13-sponsored-toll-bridge",
  "oz-yellow-line-signal": "13-sponsored-toll-bridge",
  "oz-yellow-line-poppies": "16-rooftop-tram-departure",
  "oz-yellow-line-gates": "14-emerald-customer-service-hall",
  "oz-behind-the-curtain-queue": "14-emerald-customer-service-hall",
  "oz-behind-the-curtain-receipts": "14-emerald-customer-service-hall",
  "oz-behind-the-curtain-projection": "14-emerald-customer-service-hall",
  "oz-behind-the-curtain-screen": "15-behind-ozs-curtain",
  "oz-behind-the-curtain-storm-plan": "16-rooftop-tram-departure",
  "oz-behind-the-curtain-tickets": "16-rooftop-tram-departure",
  "oz-behind-the-curtain-last-stop": "16-rooftop-tram-departure",
  "oz-behind-the-curtain-home": "12-yellow-line-bus-terminal",
  "oz-behind-the-curtain-shoes": "12-yellow-line-bus-terminal",
  "alice-borrowed-hour-door": "17-the-hour-lending-shop",
  "alice-borrowed-hour-sizes": "19-hallway-of-wrong-sized-doors",
  "alice-borrowed-hour-tea": "18-borrowed-hour-tea-garden",
  "alice-borrowed-hour-cups": "18-borrowed-hour-tea-garden",
  "alice-borrowed-hour-cups-puzzle": "18-borrowed-hour-tea-garden",
  "alice-borrowed-hour-grin": "18-borrowed-hour-tea-garden",
  "alice-borrowed-hour-clock": "21-the-missing-spring-clocktower",
  "alice-borrowed-hour-leave": "21-the-missing-spring-clocktower",
  "alice-borrowed-hour-summons": "20-the-queens-petty-court",
  "alice-full-stop-charge": "20-the-queens-petty-court",
  "alice-full-stop-sentence": "20-the-queens-petty-court",
  "alice-full-stop-guard": "20-the-queens-petty-court",
  "alice-full-stop-evidence": "20-the-queens-petty-court",
  "alice-full-stop-order": "20-the-queens-petty-court",
  "alice-full-stop-choice": "20-the-queens-petty-court",
  "alice-full-stop-verdict": "20-the-queens-petty-court",
  "alice-full-stop-door": "19-hallway-of-wrong-sized-doors",
  "alice-full-stop-home": "17-the-hour-lending-shop",
  "yasuke-banner-without-master-arrival": "22-festival-courtyard",
  "yasuke-banner-without-master-terms": "23-vip-sword-lesson-pavilion",
  "yasuke-banner-without-master-banners": "22-festival-courtyard",
  "yasuke-banner-without-master-lesson": "24-lantern-practice-ground",
  "yasuke-banner-without-master-contract": "23-vip-sword-lesson-pavilion",
  "yasuke-banner-without-master-challenge": "23-vip-sword-lesson-pavilion",
  "yasuke-banner-without-master-name": "22-festival-courtyard",
  "yasuke-banner-without-master-opening": "24-lantern-practice-ground",
  "yasuke-banner-without-master-bow": "24-lantern-practice-ground",
  "cellblock-library-hour-shelf": "25-cellblock-library",
  "cellblock-library-hour-rumor": "26-kingpins-reservation-desk",
  "cellblock-library-hour-forms": "26-kingpins-reservation-desk",
  "cellblock-library-hour-yard": "27-library-hour-showdown",
  "cellblock-library-hour-stamps": "25-cellblock-library",
  "cellblock-library-hour-shelves": "25-cellblock-library",
  "cellblock-library-hour-opening-match": "27-library-hour-showdown",
  "cellblock-library-hour-first-reader": "25-cellblock-library",
  "cellblock-library-hour-bookmark": "25-cellblock-library",
  "homeless-a-place-to-return-name": "29-community-kitchen-loading-bay",
  "homeless-a-place-to-return-storm": "28-rain-flooded-supply-route",
  "homeless-a-place-to-return-dry-route": "28-rain-flooded-supply-route",
  "homeless-a-place-to-return-supplies": "29-community-kitchen-loading-bay",
  "homeless-a-place-to-return-address": "30-landlords-lobby",
  "homeless-a-place-to-return-appointments": "31-housing-appointment-office",
  "homeless-a-place-to-return-space": "29-community-kitchen-loading-bay",
  "homeless-a-place-to-return-key": "32-leons-new-room",
  "homeless-a-place-to-return-return": "32-leons-new-room"
};
const CHAPTER_ENVIRONMENTS: Readonly<Record<string, string>> = {
  "s2-the-morning-after": "33-the-morning-after-rooftop",
  "s2-the-rent-party": "34-rent-party-courtyard",
  "s2-unlicensed-improvements": "35-community-space-under-repair",
  "s2-regular-guy-behavior": "35-community-space-under-repair",
  "s2-museum-of-the-block": "36-museum-of-the-block",
  "s2-everybody-has-a-buyer": "36-museum-of-the-block",
  "s2-premiere-night": "37-premiere-night-entrance",
  "s2-the-blockbuster": "37-premiere-night-entrance",
  "special-sherlock-missing-motion": "01-after-hours-block-party",
  "special-sherlock-false-bottom": "02-bootleg-film-archive",
  "special-sherlock-last-reel": "03-promoters-back-office",
  "sherlock-thirteenth-bell": "04-impossible-midnight-station",
  "sherlock-dead-air": "07-community-radio-booth",
  "sherlock-negative-space": "10-neighborhood-trophy-gallery",
  "oz-yellow-line": "12-yellow-line-bus-terminal",
  "oz-behind-the-curtain": "14-emerald-customer-service-hall",
  "alice-borrowed-hour": "17-the-hour-lending-shop",
  "alice-full-stop": "20-the-queens-petty-court",
  "yasuke-banner-without-master": "22-festival-courtyard",
  "cellblock-library-hour": "25-cellblock-library",
  "homeless-a-place-to-return": "29-community-kitchen-loading-bay"
};
const asset = (name: string) => `assets/story/environments/backgrounds/${name}.webp`;
export function withStoryEnvironments(chapters: readonly StoryChapter[]): StoryChapter[] {
  return chapters.map(chapter => {
    const map = CHAPTER_ENVIRONMENTS[chapter.id];
    if (!map) return chapter;
    return { ...chapter, mapAssetId: asset(map), nodes: chapter.nodes.map(node => {
      const name = STORY_ENVIRONMENTS[node.id];
      if (!name) throw new Error(`Missing authored environment for ${node.id}`);
      const environmentAssetId = asset(name);
      return { ...node, cinematic: { ...node.cinematic, environmentAssetId },
        ...(node.kind === 'battle' ? { battlefieldAssetId: environmentAssetId } : {}) };
    }) };
  });
}
