/** Signature scenes for the thirty-entry Street Legends release. */
export const STREET_LEGENDS_STYLE_SCENES: Record<string, readonly [string, string]> = {
  'boo-boo-the-fool': ['Wrong Address', 'night-market'],
  'mr-mc-hands': ['All These Hands', 'underground-ring'],
  'ms-mary-mack': ['Clap Back Rhythm', 'community-kitchen'],
  'pimp-swookie': ['Say the Whole Name', 'vip-section'],
  'og-uncle-harley-davidson': ['Old Head, Open Road', 'rush-hour'],
  'suga-mama': ['Auntie Got It', 'penthouse'],
  'side-chick': ['Not Your Family', 'magic-city'],
  'gas-station-window-wiper': ["You Ain't Ask", 'rush-hour'],
  'parole-officer': ['Violation', 'county-jail'],
  'work-hubby': ['Lunch Break Loyalty', 'community-kitchen'],
  'he-just-a-friend': ['He Just a Friend', 'vip-section'],
  'crazy-ex-boyfriend': ['You Up?', 'acorn-projects'],
  'uncle-sam': ['PAY WHAT YOU OWE', 'time-square'],
  'apartment-maintenance-sage': ['I GOT A KEY FOR THAT', 'acorn-projects'],
  'bail-bonds-auntie': ['Sign Here', 'county-jail'],
  'the-rapper': ['The Cypher', 'pirate-radio'],
  'the-dj': ['The Set', 'pirate-radio'],
  'the-hype-man': ['Crowd Work', 'pirate-radio'],
  'the-janky-promoter': ['Guest List', 'hollywood-strip'],
  'the-manager-nice': ['Artist First', 'pirate-radio'],
  'the-manager-evil': ['Read the Fine Print', 'vip-section'],
  'the-opening-act': ['Warm the Room', 'pirate-radio'],
  'the-local-celebrity': ['Everybody Know Me', 'hollywood-strip'],
  'the-battle-rapper': ['The Rebuttal', 'pirate-radio'],
  'the-og-rap-legend': ['Pass the Torch', 'vip-section'],
  'fitness-bro': ['One More Set', 'underground-ring'],
  'fitness-girl': ['Active Recovery', 'rooftop-garden'],
  'personal-trainer': ['One More Rep', 'underground-ring'],
  'demon-trainer': ['No Pain, No Excuses', 'underground-ring'],
  'lash-tech': ['Lash Out', 'nail-salon'],
};
