import type { AbilityUpgradeEffect, Card, CardRarity } from './data';

/** Street people and Lash Tech are separate identities; Nail Tech keeps her original save key and art. */
export const STREET_LEGENDS_WAVE = [
  ['boo-boo-the-fool', 'Boo Boo the Fool', 'Uncommon', 'Air', 2, 2, 'Wrong Address', 'On Reveal: Leave a Decoy here through next round. The next enemy character played or moved here takes 1 damage. If damage lands and Boo Boo is active, he moves to your weakest other open district and gains +1 Hand only if he arrives. One Decoy per side; each Boo Boo sets it once per match.', 'Disruption'],
  ['mr-mc-hands', 'Mr. Mc Hands', 'Epic', 'Normal', 4, 4, 'All These Hands', 'On Reveal: Hit up to two different strongest enemy characters here for 2 damage each. Each strike separately respects defenses.', 'Pressure'],
  ['ms-mary-mack', 'Ms. Mary Mack', 'Mythical', 'Normal', 2, 3, '15 Cents', 'Ongoing: At round end, collect 3¢ per enemy card on the board, up to 15¢. At 15¢, disappear and return next round as a 4 Motion / 4 Hands elephant in your weakest district with room, ignoring location locks. Keep invested Hands. All enemies there lose 1 Hand; defenses apply. Once per instance. On the final round, stay on the board.', 'Movement'],
  ['pimp-swookie', 'Pimp Swookie', 'Epic', 'Poison', 3, 3, 'Say the Whole Name', 'On Reveal: Weaken the strongest enemy here and place a Name Check on it through next round. Its next positive Hands gain is reduced by up to 2, then the check is spent. One check per side. Defenses apply; withheld gains are not damage.', 'Disruption'],
  ['og-uncle-harley-davidson', 'OG Uncle Harley Davidson', 'Legendary', 'Earth', 4, 5, 'Old Head, Open Road', 'On Reveal: Move to your weakest other open district. Only if you arrive, gain +1 Hand and give your weakest other ally there +2 Hands.', 'Movement'],
  ['suga-mama', 'Suga Mama', 'Legendary', 'Light', 3, 3, 'Auntie Got It', 'On Reveal: Give your weakest other ally anywhere +2 Hands and Cleanse it. If its district is still trailing, Protect it.', 'Support'],
  ['side-chick', 'Side Chick', 'Rare', 'Poison', 2, 2, 'Not Your Family', 'On Reveal: Hit the strongest enemy Baby Momma anywhere for 3 damage and Weaken her in one hostile package. If no enemy Baby Momma is on the board, hit the strongest enemy here for 1 instead. Defenses apply.', 'Disruption'],
  ['gas-station-window-wiper', 'Gas Station Window Wiper', 'Uncommon', 'Water', 1, 2, "You Ain't Ask", 'On Reveal: Move to your weakest other open district. Only if you arrive, hit its strongest enemy for 1.', 'Movement'],
  ['parole-officer', 'Parole Officer', 'Rare', 'Earth', 3, 3, 'Violation', 'On Reveal: Put a movement-only Curfew on the strongest enemy here through next round. Post a Check-In here through next round: the first enemy character that moves here each round takes 2 damage. One Check-In per district per side. Defenses apply; Curfew can be cleansed.', 'Disruption'],
  ['work-hubby', 'The Work Hubby', 'Uncommon', 'Normal', 2, 2, 'Lunch Break Loyalty', 'On Reveal: Protect your weakest other ally here and give it a Lunch Bond through next round. Its next genuine Hands gain gives an active Work Hubby +1 Hand. One pending Bond per side; each Work Hubby issues one per match. Shared gains do not pay.', 'Support'],
  ['he-just-a-friend', 'The Guy She Told You Not to Worry About', 'Rare', 'Air', 3, 3, 'He Just a Friend', 'On Reveal: If the strongest enemy here has more Hands than this card, move it to its weakest other open district. Gain +2 Hands only if it arrives. Otherwise Protect your weakest other ally here. Defenses and capacity apply.', 'Movement'],
  ['crazy-ex-boyfriend', 'Crazy Ex-Boyfriend', 'Epic', 'Dark', 3, 3, 'You Up?', 'On Reveal: Mark the strongest enemy anywhere for one chase at next round start. Move into its district if legal, then hit it for 2 only after arriving or if already there. In the final round, hit the strongest enemy here for 2 instead. One pending chase per side; each Ex books one per match.', 'Disruption'],
  ['uncle-sam', 'Uncle Sam', 'Legendary', 'Earth', 4, 4, 'PAY WHAT YOU OWE', 'On Reveal: Confiscate up to 3 removable bonus Hands from the local enemy with the most bonus and gain the amount actually taken. Never takes printed Hands or creates healing credit. If nobody has bonus, Audit here through next round: the next enemy character played here costs +1 Motion. One pending Audit per side.', 'Disruption'],
  ['apartment-maintenance-sage', 'Apartment Maintenance Sage', 'Rare', 'Light', 3, 3, 'I GOT A KEY FOR THAT', 'On Reveal: Cleanse your weakest other ally here and remove its timed movement restriction, then move it to your weakest other open district. Protect it only if it arrives. Capacity, district detention and story closures still apply.', 'Support'],
  ['bail-bonds-auntie', 'The Bail Bonds Auntie', 'Rare', 'Poison', 2, 2, 'Sign Here', 'On Reveal: Give your weakest other local ally a Bail Bond through next round. Redirect its next targeted hostile ability to an active Auntie once. If she takes damage or a new harmful status, arm a credit through next round: your next Poison character played in another district refunds 1 Motion after a successful entrance. One Bond and credit per side.', 'Support'],
  ['lash-tech', 'Lash Tech', 'Uncommon', 'Poison', 2, 2, 'Lash Out', 'On Reveal: Hit the strongest enemy here for 1 damage. Only if damage lands, give your weakest other ally here +2 Hands. Blocked or fully absorbed hits give no ally boost. Defenses apply.', 'Support'],
] as const;

export const streetLegendsUpgradeEffects: Record<string, readonly AbilityUpgradeEffect[]> = Object.fromEntries(STREET_LEGENDS_WAVE.map(([id]) => [id, [0, 1, 2].map(() => ({ kind: 'self-power' as const, amount: 1 as const, trigger: 'base-success' as const }))]));
export const streetLegendsRarities: Record<string, CardRarity> = Object.fromEntries(STREET_LEGENDS_WAVE.map(([id, , rarity]) => [id, rarity]));
export const streetLegendsFactions: Record<string, string> = Object.fromEntries(STREET_LEGENDS_WAVE.map(([id]) => [id, id === 'lash-tech' ? 'Beauty' : 'Street Legends']));
export const streetLegendsCards: Record<string, Card> = Object.fromEntries(STREET_LEGENDS_WAVE.map(([id, name, , type, cost, power, ability, effect, role]) => [id, {
  id, name, type, cost, power, ability, effect, roles: [role], kind: 'character', artworkLayout: 'portrait',
  abilityUpgrades: [2, 5, 8].map((unlockLevel, index) => ({ id: `${id}:upgrade:${index + 1}`, name: `${ability} ${['Practice', 'Confidence', 'Mastery'][index]}`, description: 'The first time the base ability succeeds this match, gain +1 Hand.', unlockLevel, effect: streetLegendsUpgradeEffects[id][index] })),
}]));
