import { completeEngineCrew } from '@workspace/squabblemon-engine/data';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import test from 'node:test';
import { cards, catalogCardByEngineId } from '@workspace/squabblemon-engine/data';
import { createMatch, createCardInstance, playCard, type Match } from '@workspace/squabblemon-engine/gameEngine';
import { createCardProgressionSnapshot } from './cardProgression';

test('experiment claims, match retries, and bootstrap normalization preserve one reward', {skip:!process.env.DATABASE_URL}, async t => {
  const { db, pool, playerProfilesTable, playerMatchesTable } = await import('@workspace/db');
  const { eq } = await import('drizzle-orm');
  const { ensurePlayer, getPlayerBootstrap } = await import('./playerState');
  const { claimExperimentCard, completeStandardMatchReward } = await import('./playerRewardTransactions');
  const userId = `gameplay-${randomUUID()}`;
  t.after(async () => { await db.delete(playerProfilesTable).where(eq(playerProfilesTable.clerkUserId,userId)); await pool.end(); });
  await ensurePlayer(userId);
  await db.update(playerProfilesTable).set({onboardingStep:'complete',ownedCardIds:['cornball','pinay-nurse'],storyProgress:{gameplay:{cleansed:true}},softCurrency:123}).where(eq(playerProfilesTable.clerkUserId,userId));
  const claims = await Promise.all([claimExperimentCard(userId,'young-bull'),getPlayerBootstrap(userId),claimExperimentCard(userId,'young-bull')]);
  assert.equal(claims.filter(v => v === true).length,1);
  await assert.rejects(claimExperimentCard(userId,'edgar'), /milestone/);
  let state = await getPlayerBootstrap(userId);
  assert.equal(state.profile.ownedCardIds.filter(id => id === 'young-bull').length,1);
  assert.equal(state.profile.softCurrency,123);
  assert.equal((state.profile.storyProgress.gameplay as {choices:string[]}).choices.length,1);
  const roster = completeEngineCrew(['cornball','pinaynurse','youngbull','earthy','nguyen','edgar','abuela']);
  const snapshot = createCardProgressionSnapshot(roster,[],{},true,[]);
  const [stored] = await db.insert(playerMatchesTable).values({clerkUserId:userId,mode:'practice',playerDeckId:'street-draft',rivalDeckId:'block',playerEngineCardIds:roster,playerCardProgressionSnapshot:snapshot}).returning();
  const nurse = createCardInstance('pinaynurse','player','test',0);
  const patient = {...createCardInstance('cornball','player','test',1),lane:0 as const};patient.statuses.frozen=true;
  let match: Match = {...createMatch('block','block'),playerHand:[nurse],boards:[[patient],[],[]]};
  match = playCard(match,'player',nurse.instanceId,0);
  const borrowed = createCardInstance('earthy','player','test',2);
  match = playCard({...match,phase:'player',playerMotion:2,playerHand:[borrowed]},'player',borrowed.instanceId,0);
  match = {...match,phase:'complete',round:6};
  const input = {clerkUserId:userId,matchId:stored.id,outcome:'draw' as const,districtsWon:1,verifiedMatch:match};
  const results = await Promise.all([completeStandardMatchReward(input),completeStandardMatchReward(input),getPlayerBootstrap(userId)]);
  assert.equal(results.filter(v => 'completed' in v && v.completed).length,1);
  state = await getPlayerBootstrap(userId);
  assert(state.missions.find(m=>m.title==='Clear the Air')?.progress === 1);
  assert(!state.profile.ownedCardIds.includes('earthy-sugar-foot'));
  assert(!state.profile.cardProgression['earthy-sugar-foot']);
  assert.equal(state.profile.cardProgression['pinay-nurse'].xp,25);
});
