import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {eq} from 'drizzle-orm';
import {db,playerProfilesTable,playerCollectionClaimsTable} from '@workspace/db';
import {getLegendBounties,claimLegendBounty} from './legendBounties';
import {progressBountyEvent} from './legendBountyProgress';
import {LEGEND_BOUNTIES,legendBountyStatuses,legendNodeKey,type BountyTask} from '@workspace/squabblemon-engine/legendBounties';
import {STARTER_MYTHIC} from '@workspace/squabblemon-engine/starterMythic';
async function player(t:test.TestContext){const id=`legend-bounty-${randomUUID()}`;t.after(async()=>{await db.delete(playerProfilesTable).where(eq(playerProfilesTable.clerkUserId,id));});await db.insert(playerProfilesTable).values({clerkUserId:id,ownedCardIds:[],discoveredCardIds:[],softCurrency:0,packTickets:0,styleShards:0,storyProgress:{}});return id;}
async function gate(id:string){await db.insert(playerCollectionClaimsTable).values({clerkUserId:id,milestoneKey:STARTER_MYTHIC.key,reward:{}});}
async function event(id:string,task:BountyTask,key:string=randomUUID()){await db.transaction(async tx=>{const [p]=await tx.select().from(playerProfilesTable).where(eq(playerProfilesTable.clerkUserId,id)).for('update');const storyProgress=await progressBountyEvent(tx,p,key,[task]);await tx.update(playerProfilesTable).set({storyProgress}).where(eq(playerProfilesTable.clerkUserId,id));});}
test('campaign has exact alternating order and 21 reward nodes',()=>{assert.deepEqual(LEGEND_BOUNTIES.map(b=>b.id),['block-party-titan','ashlee','p-tang','simmy','folks','kyle','foodz']);assert.equal(new Set(LEGEND_BOUNTIES.flatMap(b=>b.nodes.map(n=>legendNodeKey(b.id,n.id)))).size,21);assert.ok(legendBountyStatuses({},[],['homeless-guy'],[]).every(b=>b.state==='locked'));});
test('gate and active node prevent banking progress; replay cannot cross nodes',async t=>{const id=await player(t);await event(id,'training','early');await gate(id);assert.equal((await getLegendBounties(id))[0].nodes[0].progress,0);await event(id,'training','early');await event(id,'friendly');assert.equal((await getLegendBounties(id))[0].nodes[0].progress,0);for(let i=0;i<3;i++)await event(id,'training',`train-${i}`);await assert.rejects(()=>claimLegendBounty(id,'block-party-titan','main-stage'));const r=await Promise.all([claimLegendBounty(id,'block-party-titan','soundcheck'),claimLegendBounty(id,'block-party-titan','soundcheck')]);assert.equal(r.filter(x=>x.claimed).length,1);await event(id,'friendly','train-0');assert.equal((await getLegendBounties(id))[0].nodes[1].progress,0);const [p]=await db.select().from(playerProfilesTable).where(eq(playerProfilesTable.clerkUserId,id));assert.equal(p.softCurrency,150);assert.equal(p.ownedCardIds.length,0);});
test('full campaign pays every node once and recruits in sequence',async t=>{const id=await player(t);await gate(id);for(const b of LEGEND_BOUNTIES){for(const n of b.nodes){const statuses=await getLegendBounties(id);assert.equal(statuses.find(x=>x.id===b.id)?.currentNodeId,n.id);for(let i=0;i<n.goal;i++)await event(id,n.task);const r=await claimLegendBounty(id,b.id,n.id);assert.equal(r.claimed,true);assert.equal(r.unlocked,n===b.nodes[2]);assert.equal((await claimLegendBounty(id,b.id,n.id)).claimed,false);}}const [p]=await db.select().from(playerProfilesTable).where(eq(playerProfilesTable.clerkUserId,id));assert.equal(p.softCurrency,2800);assert.equal(p.packTickets,7);assert.equal(p.styleShards,70);assert.deepEqual(p.ownedCardIds,LEGEND_BOUNTIES.map(b=>b.id));assert.ok((await getLegendBounties(id)).every(b=>b.state==='claimed'));});

test('standard match settlement advances training once on retry',async t=>{const id=await player(t);await gate(id);const {playerMatchesTable}=await import('@workspace/db');const {createMatch}=await import('@workspace/squabblemon-engine/gameEngine');const {createCardProgressionSnapshot}=await import('./cardProgression');const {completeStandardMatchReward}=await import('./playerRewardTransactions');const [m]=await db.insert(playerMatchesTable).values({clerkUserId:id,mode:'practice',playerDeckId:'block',rivalDeckId:'slide',playerCardProgressionSnapshot:createCardProgressionSnapshot([],[],{})}).returning();const input={clerkUserId:id,matchId:m.id,outcome:'win' as const,districtsWon:3,verifiedMatch:createMatch('block','slide')};await completeStandardMatchReward(input);await completeStandardMatchReward(input);assert.equal((await getLegendBounties(id))[0].nodes[0].progress,1);const [profile]=await db.select().from(playerProfilesTable).where(eq(playerProfilesTable.clerkUserId,id));assert.equal((profile.storyProgress.growthDaily as any).counters.training,1);});
test('legacy recruits remain saved and duplicate final awards pay shards once',async t=>{const id=await player(t);await gate(id);const b=LEGEND_BOUNTIES[0];await db.update(playerProfilesTable).set({ownedCardIds:[b.id]}).where(eq(playerProfilesTable.clerkUserId,id));for(const n of b.nodes){for(let i=0;i<n.goal;i++)await event(id,n.task);const r=await claimLegendBounty(id,b.id,n.id);assert.equal(r.duplicateShards,n===b.nodes[2]?25:0);}assert.equal((await claimLegendBounty(id,b.id)).claimed,false);const [p]=await db.select().from(playerProfilesTable).where(eq(playerProfilesTable.clerkUserId,id));assert.equal(p.styleShards,35);assert.equal(p.ownedCardIds.length,1);assert.equal((await getLegendBounties(id))[1].state,'active');const old=legendBountyStatuses({},[],[],['legend-bar:foodz:v1']);assert.equal(old[6].state,'claimed');assert.equal(old[0].state,'locked');});
test('routes require authentication and reject fabricated progress',async t=>{const id=await player(t);const {default:express}=await import('express');const {default:router}=await import('../routes/legendBounties');const app=express();app.use(express.json());app.use((req,_res,next)=>{const userId=req.header('x-test-user')??null;(req as any).auth=Object.assign(()=>({userId,sessionId:'test',tokenType:'session_token',isAuthenticated:!!userId}),{[Symbol.for('@clerk/express.auth')]:true});next();});app.use('/api',router);const server=app.listen(0,'127.0.0.1');await new Promise<void>(r=>server.once('listening',r));t.after(()=>new Promise<void>(r=>server.close(()=>r())));const url=`http://127.0.0.1:${(server.address() as {port:number}).port}/api/player/rewards/legend-bounties/block-party-titan/nodes/soundcheck/claim`;assert.equal((await fetch(url,{method:'POST'})).status,401);await gate(id);const res=await fetch(url,{method:'POST',headers:{'x-test-user':id,'Content-Type':'application/json'},body:JSON.stringify({progress:999,state:'ready',userId:'other'})});assert.equal(res.status,409);assert.equal((await getLegendBounties(id))[0].nodes[0].progress,0);});
