import test from 'node:test';
import assert from 'node:assert/strict';
import type { PlayerBootstrap } from '@workspace/api-client-react';
import { rewardReceipts, revealProfileRewards } from './rewardReceipts';
import { selectedChallengeRun } from './challengeJourney';
const bootstrap = (currency: number, cards: string[] = []) => ({ profile: { id:'receipt-test', softCurrency:currency, packTickets:1, styleShards:0, streetRep:0, xp:0, ownedCardIds:cards, unlockedCosmeticIds:[] } }) as unknown as PlayerBootstrap;
test('confirmed reward receipts show only increases, deduplicate claims, and clear with account scope', () => {
  rewardReceipts.reset();
  revealProfileRewards(bootstrap(100),bootstrap(50),'spend','Purchase');
  assert.equal(rewardReceipts.current(),null);
  revealProfileRewards(bootstrap(100),bootstrap(150,['stockz']),'claim','Bounty');
  const receipt=rewardReceipts.current()!;
  assert.equal(receipt.items[0].amount,50);assert.equal(receipt.items[1].label,'STOCKZ');
  rewardReceipts.dismiss();revealProfileRewards(bootstrap(100),bootstrap(150,['stockz']),'claim','Bounty');
  assert.equal(rewardReceipts.current(),null);
  rewardReceipts.reset();
});
test('saved challenge runs stay on the road until the player explicitly continues', () => {
  const active = { id: 'active-run', status: 'active' };
  const settled = { id: 'settled-run', status: 'settled' };
  const runs = [active, settled];
  assert.equal(selectedChallengeRun(runs, null), undefined);
  assert.equal(selectedChallengeRun(runs, active.id), active);
  assert.equal(selectedChallengeRun(runs, null), undefined);
  assert.equal(selectedChallengeRun(runs, settled.id), settled);
});

const levelReceipt = (level: number) => ({ id: `level-player:${level}`, title: 'Level up', level, items: [{ label: `Level ${level}` }] });
test('level rewards wait for a results exit and hold the next screen until dismissed', () => {
  rewardReceipts.reset();
  let continued = 0, acknowledged = 0;
  rewardReceipts.deferLevel(levelReceipt(2), () => acknowledged++);
  assert.equal(rewardReceipts.current(), null, 'a profile refresh must not interrupt the victory screen');
  const cancel = rewardReceipts.leaveBattleResults(() => continued++);
  assert.equal(rewardReceipts.current()?.level, 2);
  assert.equal(continued, 0, 'the next scene must not start its audio under level-up');
  assert.equal(acknowledged, 0);
  rewardReceipts.dismiss();
  assert.equal(continued, 1);
  assert.equal(acknowledged, 1);
  cancel?.();
  rewardReceipts.dismiss();
  assert.equal(continued, 1);
  rewardReceipts.deferLevel(levelReceipt(2));
  assert.equal(rewardReceipts.leaveBattleResults(() => continued++), null, 'refreshes do not replay an acknowledged level');
  rewardReceipts.reset();
});
test('multiple earned levels make one celebration; other reward receipts remain available', () => {
  rewardReceipts.reset();
  rewardReceipts.show(levelReceipt(2));
  rewardReceipts.deferLevel(levelReceipt(4));
  rewardReceipts.deferLevel(levelReceipt(3));
  rewardReceipts.show({ id: 'haul', title: 'Earnings', items: [{ label: 'Clout', amount: 50 }] });
  assert.equal(rewardReceipts.current()?.id, 'haul');
  rewardReceipts.dismiss();
  assert.equal(rewardReceipts.current(), null);
  rewardReceipts.leaveBattleResults(() => {});
  assert.equal(rewardReceipts.current()?.level, 4);
  rewardReceipts.dismiss();
  assert.equal(rewardReceipts.current(), null);
  assert.equal(rewardReceipts.leaveBattleResults(() => {}), null);
  rewardReceipts.reset();
});
test('changing route or player cancels a deferred results action', () => {
  rewardReceipts.reset();
  let continued = 0;
  rewardReceipts.deferLevel(levelReceipt(2));
  const cancel = rewardReceipts.leaveBattleResults(() => continued++);
  cancel?.();
  rewardReceipts.dismiss();
  assert.equal(continued, 0);
  rewardReceipts.deferLevel(levelReceipt(3));
  rewardReceipts.leaveBattleResults(() => continued++);
  rewardReceipts.reset();
  rewardReceipts.dismiss();
  assert.equal(continued, 0);
  assert.equal(rewardReceipts.leaveBattleResults(() => {}), null);
});
