import bossRaidRouter from './bossRaid';
import arcadeGamesRouter from './arcadeGames';
import waffleRunRouter from './waffleRun';
import dailyCloutRouter from './dailyClout';
import { Router, type IRouter } from "express";
import healthRouter from "./health";
import playerRouter from "./player";
import collectionRouter from "./collection";
import storyRouter from "./story";
import shopRouter from "./shop";
import promoCodesRouter from './promoCodes';
import multiplayerRouter from './multiplayer';
import challengeRouter from "./challenge";
import paymentsRouter from './payments';

import stockzRouter from './stockz';
import accountRewardsRouter from './accountRewards';
import legendBountiesRouter from './legendBounties';
import starterMythicRouter from './starterMythic';
import mailRouter from './mail';
import notificationsRouter from './notifications';
import socialRouter from './social';
import eventFeedbackRouter from './eventFeedback';
import patchesRouter from './patches';

const router: IRouter = Router();

router.use(healthRouter);
router.use(dailyCloutRouter);
router.use(playerRouter);
router.use(collectionRouter);
router.use(storyRouter);
router.use(shopRouter);
router.use(promoCodesRouter);
router.use(multiplayerRouter);
router.use(challengeRouter);
router.use(paymentsRouter);
router.use(accountRewardsRouter);
router.use(starterMythicRouter);
router.use(waffleRunRouter);
router.use(arcadeGamesRouter);
router.use(bossRaidRouter);
router.use(legendBountiesRouter);
router.use(mailRouter);
router.use(notificationsRouter);
router.use(eventFeedbackRouter);
router.use(patchesRouter);
router.use(stockzRouter);
router.use(socialRouter);

export default router;
