// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/battle-current/Current.tsx": () => import("../components/mockups/battle-current/Current.tsx"),
  "./components/mockups/battle-wireframe/Upgraded.tsx": () => import("../components/mockups/battle-wireframe/Upgraded.tsx"),
  "./components/mockups/battle-workshop/ComponentWorkshop.tsx": () => import("../components/mockups/battle-workshop/ComponentWorkshop.tsx"),
  "./components/mockups/story-cinema-current/Current.tsx": () => import("../components/mockups/story-cinema-current/Current.tsx")
};
