const squabblemon = {
  Rasta: {
    name: "Rastamon",
    type: "Plant",
    ability: "Natural Cure",
    stats: { hp: 200, attack: 150, defense: 130, speed: 130 },
    sprite: "https://i.imgur.com/OH3B6YT.png",
    lore: "Chill vibes only. Prefers napping in sunbeams to actual squabbling.",
    moves: [
      {
        name: "Dreadlock Whip",
        type: "Plant",
        power: 50,
        accuracy: 95,
        pp: 15,
        maxPP: 15,
        effect: "none",
      },
      {
        name: "6 Rasclaat Eggs?!",
        type: "Fire",
        power: 70,
        accuracy: 85,
        pp: 10,
        maxPP: 10,
        effect: "sleep",
      },
      {
        name: "Irie Recharge",
        type: "Plant",
        power: 0,
        accuracy: 100,
        pp: 10,
        maxPP: 10,
        effect: "heal",
      },
    ],
  },
  Fitness: {
    name: "Fitness Bro",
    type: "Fire",
    ability: "Guts",
    stats: { hp: 230, attack: 170, defense: 130, speed: 120 },
    sprite: "https://i.imgur.com/YeMI4sr.png",
    lore: "NEVER skips leg day. Or arm day. Or any day. Fueled by pure gainz.",
    moves: [
      {
        name: "Squat Slap",
        type: "Normal",
        power: 45,
        accuracy: 90,
        pp: 15,
        maxPP: 15,
        effect: "none",
      },
      {
        name: "Protein Powder Burn",
        type: "Fire",
        power: 45,
        accuracy: 85,
        pp: 5,
        maxPP: 5,
        effect: "burn",
      },
      {
        name: "Flex on ‘Em",
        type: "Normal",
        power: 0,
        accuracy: 100,
        pp: 10,
        maxPP: 10,
        effect: "raiseDefense",
      },
    ],
  },
  Techy: {
    name: "Techy",
    type: "Electric",
    ability: "Download",
    stats: { hp: 170, attack: 150, defense: 150, speed: 190 },
    sprite: "https://i.imgur.com/m7Rup7S.png",
    lore: "Runs on caffeine and pure code. Might DDoS you for fun.",
    moves: [
      {
        name: "Keyboard Smash",
        type: "Electric",
        power: 60,
        accuracy: 90,
        pp: 15,
        maxPP: 15,
        effect: "paralysis",
      },
      {
        name: "404 Headshot",
        type: "Dark",
        power: 80,
        accuracy: 80,
        pp: 5,
        maxPP: 5,
        effect: "none",
      },
      {
        name: "Caffeine Overload",
        type: "Electric",
        power: 0,
        accuracy: 100,
        pp: 10,
        maxPP: 10,
        effect: "raiseSpeed",
      },
    ],
  },
  Vibe: {
    name: "Cool Vibe YN",
    type: "Water",
    ability: "Torrent",
    stats: { hp: 190, attack: 170, defense: 130, speed: 150 },
    sprite: "https://i.imgur.com/2n71aSJ.png",
    lore: "Smooth operator. Always hydrated and ready to slide into the DMs.",
    moves: [
      {
        name: "Splash Dat Ass",
        type: "Water",
        power: 50,
        accuracy: 95,
        pp: 15,
        maxPP: 15,
        effect: "wet",
      },
      {
        name: "Wave Check Fade",
        type: "Water",
        power: 70,
        accuracy: 85,
        pp: 10,
        maxPP: 10,
        effect: "sleep",
      },
      {
        name: "Call Girls for Gang",
        type: "Water",
        power: 0,
        accuracy: 100,
        pp: 5,
        maxPP: 5,
        effect: "heal",
      },
    ],
  },
  "9-5": {
    name: "9-5 Homie",
    type: "Rock",
    ability: "Sturdy",
    stats: { hp: 210, attack: 130, defense: 150, speed: 180 },
    sprite: "https://i.imgur.com/UkE9crR.png",
    lore: "Just trying to make it to Friday. Powered by lukewarm coffee.",
    moves: [
      {
        name: "Cubicle Clapback",
        type: "Normal",
        power: 50,
        accuracy: 90,
        pp: 15,
        maxPP: 15,
        effect: "none",
      },
      {
        name: "Overtime Overload",
        type: "Electric",
        power: 65,
        accuracy: 85,
        pp: 10,
        maxPP: 10,
        effect: "paralysis",
      },
      {
        name: "PTO Prayer",
        type: "Normal",
        power: 0,
        accuracy: 100,
        pp: 5,
        maxPP: 5,
        effect: "heal",
      },
    ],
  },
  "All Jokes Roaster": {
    name: "All Jokes Roaster",
    type: "Air",
    ability: "Prankster",
    stats: { hp: 180, attack: 170, defense: 110, speed: 180 },
    sprite: "https://i.imgur.com/qRtemtQ.png",
    lore: "Can't take anything seriously. Will ratio you into oblivion.",
    moves: [
      {
        name: "Ratio’d Receipts",
        type: "Air",
        power: 40,
        accuracy: 100,
        pp: 15,
        maxPP: 15,
        effect: "none",
      },
      {
        name: "Clapback Inferno",
        type: "Fire",
        power: 55,
        accuracy: 90,
        pp: 10,
        maxPP: 10,
        effect: "burn",
      },
      {
        name: "Dodge the Shade",
        type: "Air",
        power: 0,
        accuracy: 100,
        pp: 15,
        maxPP: 15,
        effect: "raiseSpeed",
      },
    ],
  },
  "Closet Nerd": {
    name: "Closet Nerd",
    type: "Dark",
    ability: "Unaware",
    stats: { hp: 200, attack: 140, defense: 100, speed: 170 },
    sprite: "https://i.imgur.com/knA2Yxz.png",
    lore: "Knows more about anime than you know about yourself. Don't ask.",
    moves: [
      {
        name: "Manga Smack",
        type: "Normal",
        power: 60,
        accuracy: 95,
        pp: 15,
        maxPP: 15,
        effect: "none",
      },
      {
        name: "Weeb Roast",
        type: "Fire",
        power: 55,
        accuracy: 85,
        pp: 10,
        maxPP: 10,
        effect: "burn",
      },
      {
        name: "Incognito Glow-Up",
        type: "Dark",
        power: 0,
        accuracy: 100,
        pp: 10,
        maxPP: 10,
        effect: "raiseDefense",
      },
    ],
  },
  Dysfunctional: {
    name: "Dysfunctional YN",
    type: "Fire",
    ability: "Anger Point",
    stats: { hp: 160, attack: 190, defense: 90, speed: 140 },
    sprite: "https://i.imgur.com/yA0lUbo.png",
    lore: "A walking disaster, but somehow still functioning. Handle with care.",
    moves: [
      {
        name: "Hot Mess Slap",
        type: "Fire",
        power: 55,
        accuracy: 90,
        pp: 15,
        maxPP: 15,
        effect: "burn",
      },
      {
        name: "Chaos Cookout",
        type: "Fire",
        power: 85,
        accuracy: 75,
        pp: 5,
        maxPP: 5,
        effect: "recoil",
      },
      {
        name: "Trainwreck Tantrum",
        type: "Normal",
        power: 0,
        accuracy: 100,
        pp: 15,
        maxPP: 15,
        effect: "raiseAttack",
      },
    ],
  },
  "Functional Addict": {
    name: "Functional Addict",
    type: "Water",
    ability: "Hydration",
    stats: { hp: 200, attack: 150, defense: 100, speed: 130 },
    sprite: "https://i.imgur.com/G3xfSjU.png",
    lore: "Runs on liquids that aren't always water. Surprisingly coherent.",
    moves: [
      {
        name: "Sip & Splash",
        type: "Water",
        power: 45,
        accuracy: 100,
        pp: 15,
        maxPP: 15,
        effect: "wet",
      },
      {
        name: "Henny Haze",
        type: "Dark",
        power: 60,
        accuracy: 90,
        pp: 10,
        maxPP: 10,
        effect: "sleep",
      },
      {
        name: "Sober Up Sis",
        type: "Normal",
        power: 0,
        accuracy: 100,
        pp: 5,
        maxPP: 5,
        effect: "heal",
      },
    ],
  },
  "Gamer Unemployed": {
    name: "Gamer Unemployed",
    type: "Dark",
    ability: "Truant",
    stats: { hp: 210, attack: 150, defense: 190, speed: 150 },
    sprite: "https://i.imgur.com/b5pnt7o.png",
    lore: "Peak performance involves Cheetos and minimal movement. Hasn't seen the sun in weeks.",
    moves: [
      {
        name: "Cheeto Dust Jab",
        type: "Normal",
        power: 50,
        accuracy: 95,
        pp: 15,
        maxPP: 15,
        effect: "none",
      },
      {
        name: "WiFi Crash",
        type: "Electric",
        power: 65,
        accuracy: 85,
        pp: 10,
        maxPP: 10,
        effect: "paralysis",
      },
      {
        name: "Couch Potato Power",
        type: "Normal",
        power: 0,
        accuracy: 100,
        pp: 10,
        maxPP: 10,
        effect: "raiseAttack",
      },
    ],
  },
  Gamer: {
    name: "Gamer",
    type: "Dark",
    ability: "Technician",
    stats: { hp: 190, attack: 195, defense: 90, speed: 180 },
    sprite: "https://i.imgur.com/vFvQKap.png",
    lore: "All about the K/D ratio. Might rage quit if things go badly.",
    moves: [
      {
        name: "Controller Chuck",
        type: "Normal",
        power: 50,
        accuracy: 95,
        pp: 15,
        maxPP: 15,
        effect: "none",
      },
      {
        name: "Loud Ass Logout",
        type: "Dark",
        power: 85,
        accuracy: 85,
        pp: 5,
        maxPP: 5,
        effect: "recoil",
      },
      {
        name: "Tryhard Trigger",
        type: "Normal",
        power: 0,
        accuracy: 100,
        pp: 10,
        maxPP: 10,
        effect: "raiseAttack",
      },
    ],
  },
  "Houseless Hustler": {
    name: "Homeless YN",
    type: "Rock",
    ability: "Sand Veil",
    stats: { hp: 220, attack: 170, defense: 110, speed: 120 },
    sprite: "https://i.imgur.com/LRVrieF.png",
    lore: "Resourceful survivor. Turns trash into treasure, and opponents into dust.",
    moves: [
      {
        name: "Cardboard Cut",
        type: "Normal",
        power: 50,
        accuracy: 95,
        pp: 15,
        maxPP: 15,
        effect: "none",
      },
      {
        name: "Sidewalk Stomp",
        type: "Rock",
        power: 60,
        accuracy: 85,
        pp: 10,
        maxPP: 10,
        effect: "lowerSpeed",
      },
      {
        name: "Hustle Hard",
        type: "Normal",
        power: 0,
        accuracy: 100,
        pp: 10,
        maxPP: 10,
        effect: "raiseDefense",
      },
    ],
  },
  "Night Stalker": {
    name: "Serial Shooter",
    type: "Dark",
    ability: "Intimidate",
    stats: { hp: 160, attack: 200, defense: 100, speed: 180 },
    sprite: "https://i.imgur.com/Kwe1HpA.png",
    lore: "Moves in the shadows. Definitely gives off creepy vibes.",
    moves: [
      {
        name: "Knife Nightcap",
        type: "Dark",
        power: 45,
        accuracy: 85,
        pp: 10,
        maxPP: 10,
        effect: "sleep",
      },
      {
        name: "Stalk & Snooze",
        type: "Dark",
        power: 90,
        accuracy: 65,
        pp: 5,
        maxPP: 5,
        effect: "none",
      },
      {
        name: "Killer Instinct",
        type: "Dark",
        power: 0,
        accuracy: 100,
        pp: 10,
        maxPP: 10,
        effect: "raiseAttack",
      },
    ],
  },
  Earthy: {
    name: "Earthy Dude",
    type: "Plant",
    ability: "Chlorophyll",
    stats: { hp: 210, attack: 120, defense: 200, speed: 100 },
    sprite: "https://i.imgur.com/1SuHgnZ.png",
    lore: "One with nature. Probably smells faintly of patchouli and dirt.",
    moves: [
      {
        name: "Flea Market Maul",
        type: "Plant",
        power: 40,
        accuracy: 100,
        pp: 15,
        maxPP: 15,
        effect: "wet",
      },
      {
        name: "Woke Boulder Yeet",
        type: "Rock",
        power: 65,
        accuracy: 85,
        pp: 10,
        maxPP: 10,
        effect: "lowerSpeed",
      },
      {
        name: "Shea Butter Armor",
        type: "Plant",
        power: 0,
        accuracy: 100,
        pp: 10,
        maxPP: 10,
        effect: "raiseDefense",
      },
    ],
  },
  "Techbro Rich": {
    name: "Techbro Rich",
    type: "Electric",
    ability: "Motor Drive",
    stats: { hp: 180, attack: 180, defense: 120, speed: 190 },
    sprite: "https://i.imgur.com/eJpAcGt.png",
    lore: "Disrupting the Squabblemon scene, one NFT at a time. Very rich.",
    moves: [
      {
        name: "Tesla Taze",
        type: "Electric",
        power: 55,
        accuracy: 90,
        pp: 15,
        maxPP: 15,
        effect: "paralysis",
      },
      {
        name: "NFT Nuke",
        type: "Normal",
        power: 85,
        accuracy: 70,
        pp: 5,
        maxPP: 5,
        effect: "none",
      },
      {
        name: "VC Funded Flex",
        type: "Electric",
        power: 0,
        accuracy: 100,
        pp: 10,
        maxPP: 10,
        effect: "raiseSpeed",
      },
    ],
  },
  Plug: {
    name: "Plug",
    type: "Electric",
    ability: "Static",
    stats: { hp: 190, attack: 160, defense: 130, speed: 170 },
    sprite: "https://i.imgur.com/Mal7dZQ.png",
    lore: "Got the connections. Always knows a guy who knows a guy.",
    moves: [
      {
        name: "Pack Seizure",
        type: "Electric",
        power: 45,
        accuracy: 85,
        pp: 15,
        maxPP: 15,
        effect: "paralysis",
      },
      {
        name: "Bad Deal",
        type: "Electric",
        power: 60,
        accuracy: 85,
        pp: 10,
        maxPP: 10,
        effect: "lowerSpeed",
      },
      {
        name: "Trap Phone Ting",
        type: "Dark",
        power: 0,
        accuracy: 100,
        pp: 10,
        maxPP: 10,
        effect: "raiseAttack",
      },
    ],
  },
  Scammer: {
    name: "Scammer",
    type: "Dark",
    ability: "Imposter",
    stats: { hp: 170, attack: 150, defense: 110, speed: 190 },
    sprite: "https://i.imgur.com/tvAPXl8.png",
    lore: "Probably not who they say they are. Watch your wallet.",
    moves: [
      {
        name: "Catfish Swipe",
        type: "Dark",
        power: 50,
        accuracy: 95,
        pp: 15,
        maxPP: 15,
        effect: "none",
      },
      {
        name: "Cash App Cripple",
        type: "Electric",
        power: 75,
        accuracy: 80,
        pp: 10,
        maxPP: 10,
        effect: "paralysis",
      },
      {
        name: "Fake Link Flick",
        type: "Dark",
        power: 5,
        accuracy: 100,
        pp: 10,
        maxPP: 10,
        effect: "raiseSpeed",
      },
    ],
  },
  "Smoker Jr": {
    name: "Smoker Jr",
    type: "Air",
    ability: "Cloud Nine",
    stats: { hp: 190, attack: 120, defense: 130, speed: 150 },
    sprite: "https://i.imgur.com/vdaAi7h.png",
    lore: "Permanently hazy. Might forget what move it was using mid-battle.",
    moves: [
      {
        name: "Cloud Cough",
        type: "Air",
        power: 40,
        accuracy: 100,
        pp: 15,
        maxPP: 15,
        effect: "lowerAccuracy",
      },
      {
        name: "Bong Rip Blast",
        type: "Fire",
        power: 45,
        accuracy: 95,
        pp: 15,
        maxPP: 15,
        effect: "sleep",
      },
      {
        name: "Smoke Screen Stunt",
        type: "Normal",
        power: 0,
        accuracy: 100,
        pp: 10,
        maxPP: 10,
        effect: "raiseDefense",
      },
    ],
  },
  Suburban: {
    name: "Suburban Kid",
    type: "Normal",
    ability: "Simple",
    stats: { hp: 180, attack: 130, defense: 140, speed: 200 },
    sprite: "https://i.imgur.com/LKtVgCn.png",
    lore: "Just grilled. Enjoys well-maintained lawns and quiet evenings.",
    moves: [
      {
        name: "Lawnmower Lash",
        type: "Plant",
        power: 50,
        accuracy: 95,
        pp: 15,
        maxPP: 15,
        effect: "none",
      },
      {
        name: "BBQ Blaze",
        type: "Fire",
        power: 55,
        accuracy: 85,
        pp: 10,
        maxPP: 10,
        effect: "burn",
      },
      {
        name: "Picket Fence",
        type: "Normal",
        power: 0,
        accuracy: 100,
        pp: 10,
        maxPP: 10,
        effect: "raiseDefense",
      },
    ],
  },
  "Ganger Blue": {
    name: "Ganger Blue",
    type: "Dark",
    ability: "Intimidate",
    stats: { hp: 190, attack: 170, defense: 130, speed: 150 },
    sprite: "https://i.imgur.com/7THvTR0.png",
    lore: "Claims this block. Don't make eye contact for too long.",
    moves: [
      {
        name: "Crip Corner Check",
        type: "Dark",
        power: 60,
        accuracy: 95,
        pp: 15,
        maxPP: 15,
        effect: "paralysis",
      },
      {
        name: "Mean Mug",
        type: "Normal",
        power: 0,
        accuracy: 100,
        pp: 10,
        maxPP: 10,
        effect: "lowerAttack",
      },
      {
        name: "Block Buster DP",
        type: "Rock",
        power: 75,
        accuracy: 85,
        pp: 10,
        maxPP: 10,
        effect: "none",
      },
    ],
  },
  "Ganger Red": {
    name: "Ganger Red",
    type: "Fire",
    ability: "Guts",
    stats: { hp: 180, attack: 165, defense: 120, speed: 165 },
    sprite: "https://i.imgur.com/DP4RBGB.png",
    lore: "Rival crew. Always ready to throw down and prove their turf is better.",
    moves: [
      {
        name: "Rival Rush",
        type: "Normal",
        power: 45,
        accuracy: 100,
        pp: 15,
        maxPP: 15,
        effect: "none",
      },
      {
        name: "Heated Exchange",
        type: "Fire",
        power: 80,
        accuracy: 75,
        pp: 10,
        maxPP: 10,
        effect: "burn",
      },
      {
        name: "Tag Team",
        type: "Normal",
        power: 0,
        accuracy: 100,
        pp: 10,
        maxPP: 10,
        effect: "raiseAttack",
      },
    ],
  },
  Coone: {
    name: "Coone",
    type: "Dark",
    ability: "Trader", // Assuming a custom ability, maybe 'Run Away' or 'Pickup' fits better?
    stats: { hp: 170, attack: 130, defense: 110, speed: 195 },
    sprite: "https://i.imgur.com/CSvkuRk.png",
    lore: "Loves chaos and garbage cans. Surprisingly quick.",
    moves: [
      {
        name: "Side Switcher", // Maybe 'Trash Toss'?
        type: "Normal",
        power: 40,
        accuracy: 100,
        pp: 20,
        maxPP: 20,
        effect: "none",
      },
      {
        name: "Imposter Syndrome", // Maybe 'Dumpster Dive'?
        type: "Normal",
        power: 0,
        accuracy: 100,
        pp: 5,
        maxPP: 5,
        effect: "heal", // Or maybe 'raiseEvasion'?
      },
      {
        name: "red pill pop", // Maybe 'Quick Escape'?
        type: "Dark",
        power: 65, // Seems high for this theme, maybe lower power + raise speed?
        accuracy: 85,
        pp: 15,
        maxPP: 15,
        effect: "lowerDefense", // Or 'raiseSpeed'?
      },
    ],
  },
  Rapper: {
    name: "Rapper",
    type: "Normal",
    ability: "Technician",
    stats: { hp: 200, attack: 160, defense: 130, speed: 140 },
    sprite: "https://i.imgur.com/HcWNwJT.png",
    lore: "Spits hot fire... lyrically, mostly. Always working on the next mixtape.",
    moves: [
      {
        name: "Mic Drop",
        type: "Normal",
        power: 60,
        accuracy: 85,
        pp: 10,
        maxPP: 10,
        effect: "none",
      },
      {
        name: "5 Fingers of Death",
        type: "Air",
        power: 70,
        accuracy: 65,
        pp: 5,
        maxPP: 5,
        effect: "raiseSpeed",
      },
      {
        name: "Groupie Rush",
        type: "Dark",
        power: 60,
        accuracy: 100,
        pp: 10,
        maxPP: 10,
        effect: "lowerAttack",
      },
      {
        name: "Social Media Crashout",
        type: "Dark",
        power: 60,
        accuracy: 100,
        pp: 10,
        maxPP: 10,
        effect: "recoil",
      },
    ],
  },
  "Bikelife YN": {
    name: "Bikelife YN",
    type: "Electric",
    ability: "Motor Drive",
    stats: { hp: 185, attack: 150, defense: 125, speed: 190 },
    sprite: "https://i.imgur.com/i6xU3C7.png",
    lore: "Swerving through traffic and battles. Speed is everything.",
    moves: [
      {
        name: "Wheelie Whip",
        type: "Normal",
        power: 55,
        accuracy: 95,
        pp: 15,
        maxPP: 15,
        effect: "none",
      },
      {
        name: "Exhaust Burn",
        type: "Fire",
        power: 60,
        accuracy: 90,
        pp: 10,
        maxPP: 10,
        effect: "burn",
      },
      {
        name: "Ride Out",
        type: "Electric",
        power: 0,
        accuracy: 100,
        pp: 10,
        maxPP: 10,
        effect: "raiseSpeed",
      },
      {
        name: "High-Speed Trick",
        type: "normal",
        power: 60,
        accuracy: 100,
        pp: 10,
        maxPP: 10,
        effect: "lowerAttack",
      },
    ],
  },
  Hooper: {
    name: "Hooper",
    type: "Fire",
    ability: "Guts",
    stats: { hp: 210, attack: 175, defense: 140, speed: 135 },
    sprite: "https://i.imgur.com/nmL74YQ.png",
    lore: "Got handles and heart. Plays above the rim and talks trash.",
    moves: [
      {
        name: "Ankle Breaker Combo",
        type: "Normal",
        power: 55,
        accuracy: 85,
        pp: 15,
        maxPP: 15,
        effect: "lowerSpeed",
      },
      {
        name: "Heat Check",
        type: "Fire",
        power: 75,
        accuracy: 75,
        pp: 10,
        maxPP: 10,
        effect: "none",
      },
      {
        name: "Hoop Harder",
        type: "Normal",
        power: 70,
        accuracy: 85,
        pp: 10,
        maxPP: 10,
        effect: "flinch",
      },
      {
        name: "Support Bunny",
        type: "normal",
        power: 0,
        accuracy: 100,
        pp: 5,
        maxPP: 5,
        effect: "heal",
      },
    ],
  },
  "Live Streamer": {
    name: "Live Streamer",
    type: "Electric",
    ability: "Technician",
    stats: { hp: 175, attack: 120, defense: 115, speed: 185 },
    sprite: "https://i.imgur.com/3rCsqGF.png",
    lore: "'Yo, chat! Smash that like button!' Always online, never AFK.",
    moves: [
      {
        name: "Stan Sumbission",
        type: "Normal",
        power: 40,
        accuracy: 100,
        pp: 20,
        maxPP: 20,
        effect: "none",
      },
      {
        name: "Follower Frenzy",
        type: "Normal",
        power: 10,
        accuracy: 100,
        pp: 10,
        maxPP: 10,
        effect: "raiseSpeed",
      },
      {
        name: "Donate Debuff",
        type: "Dark",
        power: 50,
        accuracy: 90,
        pp: 10,
        maxPP: 10,
        effect: "lowerDefense",
      },
    ],
  },
  "Officer Oink": {
    name: "Officer Oink",
    type: "Normal",
    ability: "Intimidate",
    stats: { hp: 230, attack: 150, defense: 160, speed: 90 },
    sprite: "https://i.imgur.com/AdCwGHp.png",
    lore: "Laying down the law, one donut break at a time.",
    moves: [
      {
        name: "Profile",
        type: "Normal",
        power: 65,
        accuracy: 95,
        pp: 15,
        maxPP: 15,
        effect: "none",
      },
      {
        name: "Body Cam Crusher",
        type: "Normal",
        power: 0,
        accuracy: 90,
        pp: 10,
        maxPP: 10,
        effect: "lowerSpeed",
      },
      {
        name: "Backup Call",
        type: "Normal",
        power: 0,
        accuracy: 100,
        pp: 5,
        maxPP: 5,
        effect: "raiseDefense",
      },
    ],
  },
  Snitch: {
    name: "Snitch",
    type: "Dark",
    ability: "Unaware",
    stats: { hp: 160, attack: 110, defense: 100, speed: 175 },
    sprite: "https://i.imgur.com/OOZM6eu.png",
    lore: "Always listening, always watching. Tells everything.",
    moves: [
      {
        name: "Tattle Tale",
        type: "Dark",
        power: 30,
        accuracy: 100,
        pp: 20,
        maxPP: 20,
        effect: "lowerDefense",
      },
      {
        name: "Run, Hide & Hate",
        type: "Normal",
        power: 0,
        accuracy: 100,
        pp: 15,
        maxPP: 15,
        effect: "raiseEvasion",
      },
      {
        name: "Expose Weakness",
        type: "Dark",
        power: 50,
        accuracy: 100,
        pp: 15,
        maxPP: 15,
        effect: "none",
      },
    ],
  },
  Cornball: {
    name: "Cornball",
    type: "Normal",
    ability: "Simple",
    stats: { hp: 210, attack: 100, defense: 120, speed: 110 },
    sprite: "https://i.imgur.com/yUUA3of.png",
    lore: "Tries way too hard to be cool. Tells terrible jokes.",
    moves: [
      {
        name: "Dad Joke",
        type: "Normal",
        power: 40,
        accuracy: 95,
        pp: 20,
        maxPP: 20,
        effect: "none",
      },
      {
        name: "Scare the Hoes",
        type: "Normal",
        power: 0,
        accuracy: 90,
        pp: 10,
        maxPP: 10,
        effect: "lowerSpeed",
      },
      {
        name: "Try Hard",
        type: "Normal",
        power: 60,
        accuracy: 90,
        pp: 15,
        maxPP: 15,
        effect: "recoil",
        effectChance: 0.1,
      },
      {
        name: "Trauma Dump",
        type: "Dark",
        power: 15,
        accuracy: 100,
        pp: 5,
        maxPP: 5,
        effect: "heal",
      },
    ],
  },
  "Jittery Junkman": {
    name: "Cracked Head",
    type: "Poison",
    ability: "Technician", // Maybe 'Poison Touch' or 'Speed Boost'?
    stats: { hp: 150, attack: 140, defense: 90, speed: 195 },
    sprite: "https://i.imgur.com/cl7GtvK.png",
    lore: "Moves fast, thinks faster... maybe too fast. Always looking for the next score.",
    moves: [
      {
        name: "Scrap Scramble",
        type: "Poison",
        power: 40,
        accuracy: 100,
        pp: 15, // Usually Poison moves have more PP
        maxPP: 20,
        effect: "poison",
      },
      {
        name: "Twitchy Takedown",
        type: "Normal",
        power: 60,
        accuracy: 85,
        pp: 15,
        maxPP: 15,
        effect: "none",
      },
      {
        name: "Fiending Focus",
        type: "Poison", // Maybe Psychic or Normal?
        power: 0,
        accuracy: 100,
        pp: 10,
        maxPP: 10,
        effect: "raiseSpeed",
      },
      {
        name: "Pookie Push", // Maybe 'Toxic Jab'?
        type: "Rock", // Poison type fits better
        power: 60, // Poison Jab is 80 power
        accuracy: 100,
        pp: 10, // Poison Jab has 20 PP
        maxPP: 10,
        effect: "raiseEvasion", // Poison Jab has 30% poison chance
      },
    ],
  },
  // --- NEW CHARACTERS START ---
  Wifey: {
    name: "Wifey",
    type: "Normal",
    ability: "Natural Cure",
    stats: { hp: 200, attack: 140, defense: 140, speed: 130 },
    sprite: "https://i.imgur.com/A5PCIcJ.png",
    lore: "Loyal and supportive, but don't test her patience. Keeps the gang grounded.",
    moves: [
      {
        name: "Side Eye Glare",
        type: "Dark",
        power: 0,
        accuracy: 100,
        pp: 15,
        maxPP: 15,
        effect: "lowerAttack",
        effectChance: 1.0,
      },
      {
        name: "Dinner's Ready",
        type: "Normal",
        power: 0,
        accuracy: 100,
        pp: 10,
        maxPP: 10,
        effect: "heal", // Heals user
      },
      {
        name: "Purse Smack",
        type: "Normal",
        power: 60,
        accuracy: 95,
        pp: 15,
        maxPP: 15,
        effect: "none",
      },
    ],
  },
  "Boss Babe": {
    name: "Boss Babe",
    type: "Electric",
    ability: "Download",
    stats: { hp: 180, attack: 160, defense: 110, speed: 190 },
    sprite: "https://i.imgur.com/QuHCQsK.png",
    lore: "Always closing deals and taking names. Runs on coffee and ambition.",
    moves: [
      {
        name: "Power Suit Press",
        type: "Normal",
        power: 55,
        accuracy: 95,
        pp: 15,
        maxPP: 15,
        effect: "none",
      },
      {
        name: "Synergy Shock",
        type: "Electric",
        power: 60,
        accuracy: 90,
        pp: 15,
        maxPP: 15,
        effect: "paralysis", // Apply paralysis effect
        effectChance: 0.3, // Standard chance for paralysis
      },
      {
        name: "Network Boost",
        type: "Electric",
        power: 0,
        accuracy: 100,
        pp: 10,
        maxPP: 10,
        effect: "raiseSpeed", // Raise user's speed
      },
    ],
  },
  "Snow Bunny": {
    name: "Snow Bunny",
    type: "Water", // Changed to Water for thematic fit
    ability: "Simple", // Doubles stat changes
    stats: { hp: 190, attack: 130, defense: 110, speed: 170 },
    sprite: "https://i.imgur.com/JoAlXML.png",
    lore: "Chills with the crew, brings a different kind of cool. Might freeze you out.",
    moves: [
      {
        name: "Icy Stare",
        type: "Water",
        power: 0,
        accuracy: 90,
        pp: 15,
        maxPP: 15,
        effect: "lowerSpeed", // Lower target speed
        effectChance: 1.0,
      },
      {
        name: "Designer Bag Bash",
        type: "Normal",
        power: 65,
        accuracy: 90,
        pp: 15,
        maxPP: 15,
        effect: "none",
      },
      {
        name: "Cold Shoulder",
        type: "Water",
        power: 0,
        accuracy: 100,
        pp: 10,
        maxPP: 10,
        effect: "raiseDefense", // Raise user's defense
      },
    ],
  },
  "9-5 Homegirl": {
    name: "9-5 Homegirl",
    type: "Normal",
    ability: "Sturdy",
    stats: { hp: 210, attack: 135, defense: 145, speed: 120 },
    sprite: "https://i.imgur.com/lErpjyS.png",
    lore: "Clocking in and out. Just trying to make it through the week for brunch.",
    moves: [
      {
        name: "Stapler Slam",
        type: "Normal",
        power: 50,
        accuracy: 95,
        pp: 15,
        maxPP: 15,
        effect: "none",
      },
      {
        name: "Deadline Dread",
        type: "Dark",
        power: 0,
        accuracy: 90,
        pp: 10,
        maxPP: 10,
        effect: "lowerSpeed", // Lower target speed
        effectChance: 1.0,
      },
      {
        name: "Coffee Break Heal",
        type: "Normal",
        power: 0,
        accuracy: 100,
        pp: 10,
        maxPP: 10,
        effect: "heal", // Heal user
      },
    ],
  },
  "Baby Momma": {
    name: "Baby Momma",
    type: "Fire",
    ability: "Anger Point",
    stats: { hp: 200, attack: 180, defense: 100, speed: 110 },
    sprite: "https://i.imgur.com/P4gflgs.png",
    lore: "Fiercely protective and demanding. Don't mess with her or her shorty.",
    moves: [
      {
        name: "Child Support Chokehold",
        type: "Dark",
        power: 60,
        accuracy: 90,
        pp: 10,
        maxPP: 10,
        effect: "lowerDefense", // Lower target defense
        effectChance: 0.3,
      },
      {
        name: "Stroller Slam",
        type: "Normal",
        power: 70,
        accuracy: 85,
        pp: 15,
        maxPP: 15,
        effect: "none",
      },
      {
        name: "Mama Bear Roar",
        type: "Fire",
        power: 0,
        accuracy: 100,
        pp: 10,
        maxPP: 10,
        effect: "raiseAttack", // Raise user's attack
      },
    ],
  },
  "E Girl": {
    name: "E Girl",
    type: "Dark",
    ability: "Technician",
    stats: { hp: 170, attack: 155, defense: 105, speed: 195 },
    sprite: "https://i.imgur.com/YOMc1mC.png",
    lore: "Lives online, master of aesthetics and mood swings. Probably has a Discord server.",
    moves: [
      {
        name: "Simp Swipe", // Benefits from Technician
        type: "Dark",
        power: 40,
        accuracy: 100,
        pp: 20,
        maxPP: 20,
        effect: "none",
      },
      {
        name: "RGB Rave",
        type: "Electric",
        power: 0,
        accuracy: 95,
        pp: 15,
        maxPP: 15,
        effect: "lowerAccuracy", // Lower target accuracy
        effectChance: 1.0,
      },
      {
        name: "Logout Ghost",
        type: "Dark",
        power: 0,
        accuracy: 100,
        pp: 10,
        maxPP: 10,
        effect: "raiseEvasion", // Raise user's evasion
      },
    ],
  },
  // --- NEW CHARACTERS END ---
};

const abilities = {
  "Natural Cure": "Heals status conditions upon switching out.",
  Guts: "Attack is boosted by 50% if statused (burn, paralysis, sleep, poison, freeze).",
  Download:
    "Compares opponent's Defense and Special Defense. Raises user's Attack or Special Attack corresponding to the lower stat.",
  Torrent: "Powers up Water-type moves by 50% when at 1/3 HP or less.",
  Sturdy:
    "If the Pokémon is at full HP, it survives one hit with at least 1 HP. Immune to OHKO moves.",
  Prankster: "Status moves have +1 priority.",
  Unaware:
    "Ignores the opponent's stat changes when attacking or taking damage.",
  "Anger Point": "Maximizes Attack stat if hit by a critical hit.",
  Hydration: "Heals status conditions at the end of the turn if it is raining.",
  Truant: "The Pokémon loafs around and can't attack every other turn.",
  Technician: "Powers up moves with a base power of 60 or less by 50%.",
  "Sand Veil":
    "Boosts Evasion by 25% during a sandstorm. Immune to sandstorm damage.",
  Intimidate:
    "Lowers the opponent's Attack stat by one stage upon entering battle.",
  Chlorophyll: "Doubles Speed stat during harsh sunlight.",
  "Motor Drive":
    "Raises Speed by one stage if hit by an Electric-type move; grants immunity to Electric-type moves.",
  Static: "30% chance of paralyzing an opponent when hit by a contact move.",
  Imposter: "Transforms into the opponent upon entering battle.",
  "Cloud Nine": "Negates all weather effects while the Pokémon is active.",
  Simple: "The Pokémon's stat changes are doubled.",
  "Poison Touch":
    "30% chance of poisoning the target when using a contact move.",
  Trader: "Custom ability - functionality undefined in current code.", // Added description for custom ability
  Soundproof: "Grants immunity to sound-based moves.", // Added description for potential DJ ability
  Pickup: "May pick up items after battles.", // Added description for potential Bodega Cat ability
};

const typeAdvantages = {
  Fire: { strong: ["Plant"], weak: ["Water", "Rock"] },
  Plant: { strong: ["Rock", "Water"], weak: ["Fire", "Air"] },
  Rock: { strong: ["Electric", "Fire", "Air"], weak: ["Plant", "Water"] },
  Water: { strong: ["Fire", "Rock"], weak: ["Electric", "Plant"] },
  Electric: { strong: ["Water", "Air"], weak: ["Rock", "Plant"] },
  Air: { strong: ["Plant"], weak: ["Electric", "Rock"] },
  Dark: { strong: [], weak: ["Normal"] }, // Dark is weak to Fighting, Bug, Fairy in Pokemon, but those types aren't here. Let's make it weak to Normal for balance.
  Normal: { strong: [], weak: ["Rock"] }, // Normal doesn't hit Ghost, weak vs Rock/Steel. Only Rock is present.
  Poison: { strong: ["Plant"], weak: ["Rock", "Poison"] }, // Poison is weak to Poison, Ground, Rock, Ghost. Steel immune. Only Rock/Poison present.
};

const battleBackgrounds = [
  "https://i.imgur.com/PamT0O9.png",
  "https://i.imgur.com/EQqkKah.jpeg",
  "https://i.imgur.com/f9mzhRU.png",
  "https://i.imgur.com/5vRDadh.png",
  "https://i.imgur.com/m9NrIpy.png",
  "https://i.imgur.com/pEs4HJ5.jpeg",
  "https://i.imgur.com/VTeIMuN.png",
  "https://i.imgur.com/LhIaHVy.png",
  "https://i.imgur.com/OdKFwva.png",
];

const effects = {
  fireAttack: "https://i.imgur.com/3USea8S.gif",
  fireStatus: "https://i.imgur.com/3USea8S.gif",
  waterAttack: "https://i.imgur.com/Js2eCxM.gif",
  waterStatus: "https://i.gifer.com/X5Nb.gif",
  waterBuff: "https://i.gifer.com/3q60.gif",
  electricAttack: "https://i.gifer.com/Z9pp.gif",
  electricStatus: "https://i.gifer.com/Z9pp.gif",
  plantAttack: "https://i.imgur.com/19gsngc.gif",
  rockAttack: "https://i.imgur.com/FifhqTg.gif",
  airAttack: "https://i.gifer.com/3klP.gif",
  darkAttack: "https://i.gifer.com/WXfF.gif",
  darkStatus: "https://i.gifer.com/3iCN.gif",
  darkBuff: "https://i.gifer.com/Dzpn.gif",
  normalAttack: "https://i.gifer.com/Yecx.gif",
  poisonAttack: "https://i.gifer.com/X5Nb.gif", // Reusing water status, maybe find a better poison one?
  poisonStatus: "https://i.gifer.com/3iCN.gif", // Reusing dark status
  sleepStatus: "https://i.imgur.com/hFYQ7oe.gif",
  healEffect: "https://i.imgur.com/684Bb2r.gif",
  lightEffect: "https://i.gifer.com/OkV7.gif", // Good for accuracy/evasion buffs
  genericBuff: "https://i.gifer.com/XZ5L.gif", // Generic stat up
  genericDebuff: "https://i.gifer.com/3iCN.gif", // Generic stat down
  blastAttack: "https://i.gifer.com/XZ5N.gif", // Explosive normal attack
  moneyAttack: "https://i.gifer.com/xt.gif", // For NFT Nuke
  earthyAttack: "https://i.imgur.com/19gsngc.gif", // Reusing plant
  scammerBuff: "https://i.imgur.com/6qOIOiu.gif",
  scammerEffect: "https://i.imgur.com/Z9i2lVU.gif",
  nineToFiveBuff: "https://i.gifer.com/yvL.gif",
  plugEffect: "https://i.gifer.com/3vIR.gif",
  plugDysSerBuff: "https://i.gifer.com/YyBN.gif",
  smokerFuncBuff: "https://i.gifer.com/1pOk.gif",
  winHands: "https://i.gifer.com/1uIf.gif",
  winScreen: "https://i.gifer.com/ZJF0.gif",
  loseScreen: "https://i.gifer.com/Z6W8.gif",
  jcoleHeal: "https://i.imgur.com/684Bb2r.gif",
  nbaBuff: "https://i.gifer.com/YyBN.gif",
  weedSleep: "https://i.imgur.com/hFYQ7oe.gif",
  // Removed effects for Street Artist/Bodega Cat
  // sprayPaintDebuff: "https://i.gifer.com/origin/e1/e10061c5632d3174f98046371a7b9751_w200.gif",
  // scratchAttack: "https://i.gifer.com/origin/c2/c2d76975c7863954b8697788640b461f_w200.gif",
};

window.SQUABBLEMON = squabblemon;
window.SQUABBLE_ABILITIES = abilities;
window.SQUABBLE_TYPES = typeAdvantages;
window.SQUABBLE_BACKGROUNDS = battleBackgrounds;
window.SQUABBLE_EFFECTS = effects;
