import {test,expect} from '@playwright/test';
import {LEGEND_BOUNTIES,legendBountyStatuses} from '../../../lib/squabblemon-engine/src/legendBounties';
const fixture='/e2e/bounty-gang.fixture.html?screen=bounties&scenario=ready';
test.beforeEach(async({page})=>{await page.route('**/api/player/rewards/john-henry',r=>r.fulfill({json:{state:'locked',ownsCard:false,chapters:[]}}));});
async function setup(page:any){await page.route('**/api/player/rewards/legend-bounties', (r:any)=>r.fulfill({json:legendBountyStatuses({},[],[],[])}));await page.route('**/api/player/rewards/starter-mythic',(r:any)=>r.fulfill({json:{state:'locked',ownsCard:false,chapters:[]}}));await page.goto(fixture);}
for(const viewport of [{width:1440,height:1000},{width:390,height:844}])test(`bar scene and collect all ${viewport.width}`,async({page})=>{await page.setViewportSize(viewport);await setup(page);await expect(page.locator('.legend-seat')).toHaveCount(7);for(const b of LEGEND_BOUNTIES)await expect(page.getByRole('heading',{name:b.name,exact:true})).toBeVisible();await expect(page.locator('.legend-seat__portrait img').first()).toHaveCSS('filter',/brightness\(0\)/);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`e2e/screenshots/bounty-premium-${viewport.width}.png`,fullPage:true});let count=0;await page.route('**/api/player/missions/*/claim',async r=>{count++;const current=await page.evaluate(()=>window.__bountyGangFixture.cachedBootstrap());await r.fulfill({json:{...current,profile:{...current.profile,softCurrency:current.profile.softCurrency+125},missions:current.missions.map(m=>({...m,status:m.status==='claimable'?'claimed':m.status}))}});});await page.getByRole('button',{name:'Collect all · 1'}).click();await expect.poll(()=>count).toBe(1);await expect(page.getByRole('button',{name:'Collect all · 0'})).toBeDisabled();expect((await page.evaluate(()=>window.__bountyGangFixture.cachedBootstrap())).profile.softCurrency).toBe(1125);});
test('campaign node payout and final recruitment use themed dialogs',async({page})=>{
 await page.emulateMedia({reducedMotion:'reduce'});
 const gate='starter-mythic:nothing-to-lose:v1';const id=LEGEND_BOUNTIES[0].id;const first=LEGEND_BOUNTIES[0].nodes[0];
 const statuses=legendBountyStatuses({},[],[],[gate],{[`legend-bar:${id}:node:${first.id}:v2`]:first.goal});
 await page.route('**/api/player/rewards/legend-bounties',r=>r.fulfill({json:statuses}));await page.route('**/api/player/rewards/starter-mythic',r=>r.fulfill({json:{state:'locked',ownsCard:false,chapters:[]}}));await page.goto(fixture);
 await page.locator('.bounty-contract-trail button').first().click();await expect(page.locator('.bounty-journey')).toBeVisible();await expect(page.locator('.bounty-path li')).toHaveCount(3);
 await page.route('**/api/player/rewards/legend-bounties/*/nodes/*/claim',async r=>{const current=await page.evaluate(()=>window.__bountyGangFixture.cachedBootstrap());await r.fulfill({json:{claimed:true,id,nodeId:first.id,unlocked:false,duplicateShards:0,reward:first.reward,bootstrap:{...current,profile:{...current.profile,softCurrency:1150}},statuses:legendBountyStatuses({},[],[],[gate,`legend-bar:${id}:node:${first.id}:v2`])}});});
 await page.getByRole('button',{name:'Collect node reward'}).click();await expect(page.locator('.bounty-unlock')).toBeVisible();await expect(page.locator('.bounty-unlock')).toContainText('BOUNTY NODE COMPLETE');await page.locator('.bounty-unlock').screenshot({path:'e2e/screenshots/bounty-node-payout.png'});await page.getByRole('button',{name:'Continue bounty',exact:true}).last().click();await expect(page.locator('.bounty-node-brief h3')).toHaveText('Invite the Block');
});
test('each legend has distinct themed artwork and inspectable locked missions',async({page})=>{
 await page.setViewportSize({width:390,height:844});await setup(page);
 const animations=new Set<string>();for(const b of LEGEND_BOUNTIES){await page.locator('.bounty-contract-trail button').filter({hasText:b.name}).click();await expect(page.locator('.bounty-journey')).toHaveAttribute('data-theme',b.theme);await expect(page.locator('.bounty-path li')).toHaveCount(3);animations.add(await page.locator('.bounty-theme-motion i').first().evaluate(n=>getComputedStyle(n).animationName));expect(await page.locator('.bounty-journey').evaluate(n=>n.scrollWidth<=n.clientWidth)).toBe(true);await page.locator('.bounty-journey').screenshot({path:`e2e/screenshots/bounty-journey-${b.id}.png`});await page.getByRole('button',{name:'Close bounty journey'}).click();}expect(animations.size).toBe(7);
});
test('bar scene portraits load and phone gallery has no horizontal overflow',async({page})=>{await page.setViewportSize({width:390,height:844});await setup(page);await page.locator('.legend-bar').scrollIntoViewIfNeeded();for(const image of await page.locator('.legend-seat__portrait img').all())expect(await image.evaluate((n:HTMLImageElement)=>n.complete&&n.naturalWidth>0)).toBe(true);await page.screenshot({path:'e2e/screenshots/legend-bar-phone.png'});await page.setViewportSize({width:1440,height:1000});await page.locator('.legend-bar').scrollIntoViewIfNeeded();await page.screenshot({path:'e2e/screenshots/legend-bar-desktop.png'});});
test('revised minigun appears only for collection and uses transparent aligned sprites',async({page})=>{
 await page.setViewportSize({width:1440,height:1000});await setup(page);const gun=page.getByTestId('bounty-pistol');await expect(gun).toHaveCSS('opacity','0');
 for(const img of await gun.locator('img').all()){await expect(img).toHaveAttribute('src',/bounty-hunter\/v3\/minigun-/);expect(await img.evaluate((node:HTMLImageElement)=>{const c=document.createElement('canvas');c.width=node.naturalWidth;c.height=node.naturalHeight;const x=c.getContext('2d')!;x.drawImage(node,0,0);const pixels=x.getImageData(0,0,c.width,c.height).data;let visible=false,transparent=false;for(let i=3;i<pixels.length;i+=4){visible ||= pixels[i]>0;transparent ||= pixels[i]===0;}return visible&&transparent;})).toBe(true);}
 await page.route('**/api/player/missions/*/claim',async r=>{const current=await page.evaluate(()=>window.__bountyGangFixture.cachedBootstrap());await r.fulfill({json:{...current,missions:current.missions.map(m=>({...m,status:m.status==='claimable'?'claimed':m.status}))}});});await page.getByRole('button',{name:'Collect all · 1'}).click();await expect(gun).toHaveAttribute('data-phase','firing');await page.screenshot({path:'e2e/screenshots/bounty-urban-minigun.png'});await expect(gun).toHaveAttribute('data-phase','idle');await expect(gun).toHaveCSS('opacity','0');
});
test('wanted wall and seated unlock assets keep seven separate seat spaces',async({page})=>{
 const statuses=legendBountyStatuses({cleansed:true,movementWin:true},['mastery:a','mastery:b','mastery:c','badge:after-hours','badge:street-draft','badge:neighborhood'],LEGEND_BOUNTIES.map(b=>b.id),[]);
 await page.route('**/api/player/rewards/legend-bounties',r=>r.fulfill({json:statuses}));await page.route('**/api/player/rewards/starter-mythic',r=>r.fulfill({json:{state:'locked',ownsCard:false,chapters:[]}}));
 for(const width of [1440,390]){
  await page.setViewportSize({width,height:1000});await page.goto(fixture);await expect(page.locator('.legend-seat__flier')).toHaveCount(7);await page.locator('.legend-bar').scrollIntoViewIfNeeded();
  for(const img of await page.locator('.legend-seat__portrait img').all()){
   await expect(img).toHaveAttribute('src',/bounty-hunter\/v4\/characters\//);
   expect(await img.evaluate((n:HTMLImageElement)=>n.complete&&n.naturalWidth>0)).toBe(true);
   expect(await img.evaluate((n:HTMLImageElement)=>{const c=document.createElement('canvas');c.width=n.naturalWidth;c.height=n.naturalHeight;const x=c.getContext('2d')!;x.drawImage(n,0,0);const p=x.getImageData(0,0,c.width,c.height).data;let clear=false,visible=false;for(let i=3;i<p.length;i+=4){clear ||=p[i]===0;visible ||=p[i]>200;}return clear&&visible;})).toBe(true);
  }
  const boxes=await page.locator('.legend-seat__portrait').evaluateAll(nodes=>nodes.map(n=>{const r=n.getBoundingClientRect();return{x:r.x,y:r.y,right:r.right,bottom:r.bottom};}));
  for(let i=0;i<boxes.length;i++)for(let j=i+1;j<boxes.length;j++){const a=boxes[i],b=boxes[j];expect(a.right<=b.x||b.right<=a.x||a.bottom<=b.y||b.bottom<=a.y).toBe(true);}
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:`e2e/screenshots/legend-seated-${width}.png`});
 }
});
test('final reward celebrates recruitment and continues to Ashlee without forced navigation',async({page})=>{
 await page.emulateMedia({reducedMotion:'reduce'});await page.setViewportSize({width:390,height:844});
 const b=LEGEND_BOUNTIES[0],n=b.nodes[2],gate='starter-mythic:nothing-to-lose:v1';const keys=[gate,...b.nodes.slice(0,2).map(n=>`legend-bar:${b.id}:node:${n.id}:v2`)];
 await page.route('**/api/player/rewards/legend-bounties',r=>r.fulfill({json:legendBountyStatuses({},[],[],keys,{[`legend-bar:${b.id}:node:${n.id}:v2`]:n.goal})}));await page.route('**/api/player/rewards/starter-mythic',r=>r.fulfill({json:{state:'locked',ownsCard:false,chapters:[]}}));await page.goto(fixture);
 await page.route('**/api/player/rewards/legend-bounties/*/nodes/*/claim',async r=>{const c=await page.evaluate(()=>window.__bountyGangFixture.cachedBootstrap());await r.fulfill({json:{claimed:true,nodeId:n.id,unlocked:true,duplicateShards:0,reward:n.reward,bootstrap:{...c,profile:{...c.profile,softCurrency:1250,styleShards:c.profile.styleShards+10}},statuses:legendBountyStatuses({},[],[b.id],[...keys,`legend-bar:${b.id}:node:${n.id}:v2`,`legend-bar:${b.id}:v1`])}});});
 await page.locator('.bounty-contract-trail button').first().click();await page.getByRole('button',{name:'Recruit '+b.name,exact:true}).click();await expect(page.locator('.bounty-unlock')).toContainText('LEGEND RECRUITED');await expect(page.locator('.bounty-unlock-character')).toHaveCSS('animation-name','none');expect(await page.locator('.bounty-unlock').evaluate(n=>n.scrollWidth<=n.clientWidth)).toBe(true);await page.locator('.bounty-unlock').screenshot({path:'e2e/screenshots/bounty-recruit-phone.png'});await page.setViewportSize({width:1440,height:1000});await page.locator('.bounty-unlock').screenshot({path:'e2e/screenshots/bounty-recruit-desktop.png'});await page.getByRole('button',{name:'Next bounty · Ashlee'}).click();await expect(page.locator('#bounty-journey-title')).toHaveText('Ashlee');expect(page.url()).toContain('bounty-gang.fixture');
});
