import {test,expect} from '@playwright/test';
test.beforeEach(async({page})=>{await page.route('**/api/player/rewards/john-henry',r=>r.fulfill({json:{state:'locked',ownsCard:false,chapters:[]}}));});
for(const width of [1440,390,320])test(`compact garden and cycle-three recruitment ${width}`,async({page})=>{
 await page.setViewportSize({width,height:width===320?740:900});await page.emulateMedia({reducedMotion:'reduce'});await page.goto(`/e2e/growth-lab.fixture.html?plants=20&tasks=2&motion=reduce&id=three-${width}-${Date.now()}`);
 await expect(page.locator('.growth-plant')).toHaveCount(6);await expect(page.locator('.growth-tasks li')).toHaveCount(3);await expect(page.locator('.growth-roadmap li')).toHaveCount(3);
 expect(await page.locator('.growth-clipboard').evaluate(n=>{const r=n.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth;})).toBe(true);expect(await page.locator('.growth-can').evaluate(n=>{const r=n.getBoundingClientRect();const hero=n.parentElement!.getBoundingClientRect();return r.left+r.width/2>hero.left+hero.width/2;})).toBe(true);
 for(const plant of await page.locator('.growth-plant').all()){expect(await plant.evaluate(n=>{const r=n.getBoundingClientRect(),d=n.closest('dialog')!,dr=d.getBoundingClientRect();return r.left>=dr.left&&r.right<=dr.right&&r.top-dr.top+d.scrollTop>=0&&r.bottom-dr.top+d.scrollTop<=d.scrollHeight;})).toBe(true);}
 for(const image of await page.locator('.growth-plant svg image').all())await expect(image).toHaveAttribute('href',/buddy-growth\/plants/);
 await page.screenshot({path:`e2e/screenshots/growth-compact-${width}.png`});await page.getByRole('button',{name:'Check in',exact:true}).click();await expect(page.locator('.character-recruitment')).toHaveAttribute('data-character','buddy');await expect(page.locator('.character-recruitment')).toContainText('Three Gardens');await page.getByRole('button',{name:'Keep going',exact:true}).click();await expect(page.locator('.growth-roadmap')).toContainText('Every future cycle');const saved=await page.evaluate(()=>window.growthFixture.snapshot());expect(saved.bootstrap.profile.ownedCardIds).toContain('buddy');expect(saved.status.growth.completedGardens).toBe(3);await page.getByRole('button',{name:'Close Growth Lab'}).click();await expect(page.locator('dialog[open]')).toHaveCount(0);
});
for(const id of ['homeless-guy','john-henry'])test(`special recruitment art ${id}`,async({page})=>{await page.goto(`/e2e/growth-lab.fixture.html?recruit=${id}&motion=reduce&id=${Date.now()}`);const dialog=page.locator('.character-recruitment');await expect(dialog).toHaveAttribute('data-character',id);await expect(dialog.locator('img')).toBeVisible();expect(await dialog.locator('img').evaluate((n:HTMLImageElement)=>n.complete&&n.naturalWidth>0)).toBe(true);await dialog.screenshot({path:`e2e/screenshots/unlock-${id}.png`});await page.getByRole('button',{name:'Close character unlock'}).click();await expect(dialog).toHaveCount(0);});
test('Homeless Guy claim opens celebration only after saved reward',async({page})=>{
 await page.route('**/api/player/rewards/legend-bounties',r=>r.fulfill({json:[]}));await page.route('**/api/player/rewards/starter-mythic',r=>r.fulfill({json:{state:'ready',ownsCard:false,chapters:[]}}));await page.goto('/e2e/bounty-gang.fixture.html?screen=bounties');await page.route('**/api/player/rewards/starter-mythic/claim',async r=>{const c=await page.evaluate(()=>window.__bountyGangFixture.cachedBootstrap());await r.fulfill({json:{claimed:true,duplicateShards:0,status:{state:'claimed',ownsCard:true,chapters:[]},bootstrap:c}});});await page.locator('.starter-mythic-banner').click();await page.getByRole('button',{name:'Claim your Mythic'}).click();await expect(page.locator('.character-recruitment')).toHaveAttribute('data-character','homeless-guy');await expect(page.locator('.character-recruitment')).toContainText('+1000');await expect(page.locator('.starter-mythic-dialog')).not.toBeVisible();
});
test('failed watering retries without losing plants or paying twice',async({page})=>{await page.emulateMedia({reducedMotion:'reduce'});await page.goto(`/e2e/growth-lab.fixture.html?plants=6&tasks=2&motion=reduce&failure=water&id=retry-${Date.now()}`);await page.getByRole('button',{name:'Check in',exact:true}).click();await expect(page.locator('.growth-error')).toBeVisible();await expect(page.locator('.growth-plant')).toHaveCount(6);await page.locator('.growth-error button').click();await expect(page.locator('.growth-bonus')).toBeVisible();const saved=await page.evaluate(()=>window.growthFixture.snapshot());expect(saved.waterCalls).toBe(2);expect(saved.receipts.filter(r=>r.key.startsWith('growth:garden:'))).toHaveLength(1);await expect(page.locator('.growth-plant')).toHaveCount(7);});
test('all seven plants stay inside the unclipped scroll perimeter',async({page})=>{for(const width of [1440,390,320]){await page.setViewportSize({width,height:900});await page.goto(`/e2e/growth-lab.fixture.html?plants=7&tasks=0&motion=reduce&id=fan-${width}-${Date.now()}`);await expect(page.locator('.growth-plant')).toHaveCount(7);for(const plant of await page.locator('.growth-plant').all())expect(await plant.evaluate(n=>{const r=n.getBoundingClientRect(),d=n.closest('dialog')!,dr=d.getBoundingClientRect();return r.left>=dr.left&&r.right<=dr.right&&r.top-dr.top+d.scrollTop>=0&&r.bottom-dr.top+d.scrollTop<=d.scrollHeight;})).toBe(true);await page.locator('.growth-dialog').evaluate(n=>n.scrollTop=n.scrollHeight);await page.screenshot({path:`e2e/screenshots/growth-fan-bottom-${width}.png`});}});
