import type { PlayerBootstrap } from '@workspace/api-client-react';
export function createBootstrap(): PlayerBootstrap {
  const timestamp = new Date(0);
  return {
    profile: {
      id: 'season-theater-fixture-player',
      displayName: 'Theater QA',
      avatarKey: 'cornball',
      onboardingStep: 'complete',
      starterDeckId: null,
      streetRep: 68,
      xp: 400,
      level: 3,
      softCurrency: 2500,
      packTickets: 3,
      styleShards: 250,
      packPity: 0,
      deckSlots: 4,
      cosmeticCurrency: 0,
      collectionProgress: 0,
      storyChapter: 9,
      storyNode: 2,
      tutorialCompleted: true,
      starterRewardClaimed: true,
      ageConfirmedAt: timestamp,
      termsAcceptedAt: timestamp,
      settings: { reducedMotion: false, turnTimerEnabled: false },
      ownedCardIds: [],
      discoveredCardIds: [],
      ownedVariants: [],
      equippedVariants: {},
      cardProgression: {},
      unlockedCosmeticIds: [],
      unlockedCharacterIds: [],
      savedDecks: [],
      storyProgress: {},
      inbox: [],
      packHistory: [],
      lastActiveAt: timestamp,
    },
    missions: [],
    nextAction: {
      id: 'story',
      eyebrow: 'Squabble House',
      title: 'Continue the story',
      description: 'The last waffle is missing.',
      destination: 'story',
      rewardLabel: null,
    },
    packConfig: {
      id: 'street-pack',
      name: 'Street Pack',
      oddsVersion: 'fixture',
      softCurrencyCost: 200,
      ticketCost: 1,
      rewardsPerPack: 3,
      pityLimit: 10,
      odds: [],
    },
    tenPullConfig: {
      id: 'street-ten-pull',
      name: 'Street Ten Pull',
      oddsVersion: 'fixture',
      pullCount: 10,
      ticketCost: 9,
      softCurrencyCost: 1_800,
      rewardsPerPull: 3,
      rarePityBonusPerPull: 1,
    },
    collectionRoad: [],
  };
}
