import { ParkResult } from '../src/components/ParkResult';
import { RankLadder } from '../src/components/RankArtwork';
import { Dialog } from '../src/components/ui/dialog';
import React from 'react';
import { createRoot } from 'react-dom/client';
import { ResultArtwork } from '../src/components/ResultArtwork';
import { MatchArrival } from '../src/components/MatchArrival';
import '../src/index.css';
import '../src/styles/studio.css';
import '../src/styles/result-stage.css';
const mode=new URLSearchParams(location.search).get('mode');
const action=(name:string)=>()=>{document.body.dataset.action=name};
createRoot(document.getElementById('root')!).render(mode?.startsWith('ranked-') ? <Dialog open><ParkResult outcome={mode==='ranked-loss'?'loss':mode==='ranked-draw'?'draw':'win'} ranked rank={{before:mode==='ranked-loss'?120:95,after:mode==='ranked-loss'?105:mode==='ranked-draw'?100:120,delta:mode==='ranked-loss'?-15:mode==='ranked-draw'?5:25,tier:'Bronze',outcome:mode==='ranked-loss'?'loss':mode==='ranked-draw'?'draw':'win',bot:false}} claimed={mode==='ranked-loss'?1:2} rivalClaimed={mode==='ranked-loss'?2:1} description="Six rounds. Three districts."><button className="online-primary" onClick={action('park')}>Back to Fade Park</button><button className="online-secondary" onClick={action('inspect')}>Inspect final board</button></ParkResult></Dialog> : mode==='ladder' ? <RankLadder /> : mode==='versus' ? <MatchArrival player={{name:'Guap Dad',hero:'dorothy'}} rival={{name:'The Challenger',hero:'powerhouse'}} onContinue={action('enter')} /> : <div className="result-stage result-stage--art"><ResultArtwork victory={mode!=='loss'} draw={false} results={[{player:24,cpu:12,winner:'player'},{player:8,cpu:18,winner:'cpu'},{player:30,cpu:23,winner:'player'}]} districts={[{name:'The Bodega'},{name:'The Subway'},{name:'Fade Park'}]} reward={{softCurrency:120,xp:80,streetRep:12} as any} onRegroup={action('regroup')} onTrain={action('retry')} onRebuild={action('rebuild')} actions={<nav className="result-stage__actions"><button className="studio-action studio-action--gold" onClick={action('continue')}>Continue the fade</button><button className="studio-action" onClick={action('rebuild')}>Rebuild the deck</button><button className="studio-text-action" onClick={action('home')}>Home</button></nav>}/></div>);
